B4A=true
Group=Default Group
ModulesStructureVersion=1
Type=StaticCode
Version=9.85
@EndOfDesignText@
'ModLang.bas - Modulo de Idiomas
'LockZero - Lock and ZERO worries
'Suporte multi-lingua: Portugues (pt) e Ingles (en)

Sub Process_Globals
	Private CurrentLang As String = "pt"
	Private Texts As Map
End Sub

Public Sub Init
	CurrentLang = ModSecurity.GetLanguage
	If CurrentLang = "" Then CurrentLang = "pt"
	LoadTexts
End Sub

Public Sub SetLanguage(langCode As String)
	CurrentLang = langCode.ToLowerCase
	ModSecurity.SaveLanguage(CurrentLang)
	LoadTexts
End Sub

Public Sub GetCurrentLanguage As String
	Return CurrentLang
End Sub

Public Sub GetLanguageName As String
	Select CurrentLang
		Case "pt": Return "Português"
		Case "en": Return "English"
		Case "es": Return "Español"
		Case "he": Return "עברית"
		Case Else: Return "Português"
	End Select
End Sub

'Retorna texto traduzido
Public Sub T(key As String) As String
	If Texts.IsInitialized = False Then LoadTexts
	If Texts.ContainsKey(key) Then
		Return Texts.Get(key)
	End If
	Return key 'Retorna a chave se nao encontrar
End Sub

'Alias para T()
Public Sub GetText(key As String) As String
	Return T(key)
End Sub

Private Sub LoadTexts
	Texts.Initialize

	Select CurrentLang
		Case "en": LoadEnglish
		Case "es": LoadSpanish
		Case "he": LoadHebrew
		Case Else: LoadPortuguese
	End Select
End Sub

Private Sub LoadPortuguese
	'=== APP ===
	Texts.Put("app_name", "LockZero")
	Texts.Put("app_tagline", "Lock and ZERO worries")
	Texts.Put("app_slogan", "Guarde suas informações e ZERO preocupação")
	Texts.Put("free_version", "Versão Gratuita")

	'=== GERAL ===
	Texts.Put("ok", "OK")
	Texts.Put("cancel", "Cancelar")
	Texts.Put("save", "Salvar")
	Texts.Put("delete", "Excluir")
	Texts.Put("edit", "Editar")
	Texts.Put("add", "Adicionar")
	Texts.Put("close", "Fechar")
	Texts.Put("back", "Voltar")
	Texts.Put("next", "Próximo")
	Texts.Put("continue", "Continuar")
	Texts.Put("done", "Concluído")
	Texts.Put("search", "Buscar")
	Texts.Put("search_hint", "Buscar por nome ou URL...")
	Texts.Put("search_no_results", "Nenhum resultado encontrado")
	Texts.Put("copy", "Copiar")
	Texts.Put("copied", "Copiado!")
	Texts.Put("show", "Mostrar")
	Texts.Put("hide", "Ocultar")
	Texts.Put("view", "Ver")
	Texts.Put("yes", "Sim")
	Texts.Put("no", "Não")
	Texts.Put("loading", "Carregando...")
	Texts.Put("empty", "Nenhum item")
	Texts.Put("error", "Erro")
	Texts.Put("success", "Sucesso")
	Texts.Put("warning", "Aviso")
	Texts.Put("discard", "Descartar")
	Texts.Put("discard_changes", "Descartar alterações?")
	Texts.Put("invalid_card_number", "Número do cartão inválido")

	'=== AUTENTICACAO ===
	Texts.Put("enter_passphrase", "Digite sua frase secreta")
	Texts.Put("passphrase_hint", "Sua frase pessoal...")
	Texts.Put("passphrase_confirm_new", "Confirme novamente a frase nova")
	Texts.Put("passphrase_mismatch", "As frases não coincidem")
	Texts.Put("passphrase_min_8", "Frase deve ter no mínimo 8 caracteres")
	Texts.Put("passphrase_too_short", "Frase muito curta")
	Texts.Put("confirm", "Confirmar")
	Texts.Put("unlock", "Desbloquear")
	Texts.Put("use_biometric", "Usar biometria")
	Texts.Put("wrong_passphrase", "Frase incorreta")
	Texts.Put("session_expired", "Sessão expirada")
	Texts.Put("session_remaining", "Sessão expira em")
	Texts.Put("wait_timeout", "Aguarde")
	Texts.Put("attempts", "tentativas")
	Texts.Put("failed_attempts", "tentativas incorretas")
	Texts.Put("lock", "Bloquear")
	Texts.Put("lock_confirm_msg", "Deseja bloquear a sessão agora?")
	Texts.Put("locked", "Sessão bloqueada")
	Texts.Put("session_active", "Sessão ativa")

	'=== MODO DE FRASE-SENHA ===
	Texts.Put("passphrase_mode", "Modo de frase-senha")
	Texts.Put("single_passphrase", "Frase única")
	Texts.Put("single_passphrase_desc", "Usar a mesma frase para todas as categorias")
	Texts.Put("multi_passphrase", "Frase por categoria")
	Texts.Put("multi_passphrase_desc", "Cada categoria pode ter sua própria frase")
	Texts.Put("single_passphrase_warning", "Modo frase única ativo. Para usar frases diferentes por grupo, altere em Configurações.")

	'=== CATEGORIAS ===
	Texts.Put("passwords", "Senhas")
	Texts.Put("cards", "Cartões")
	Texts.Put("documents", "Documentos")
	Texts.Put("notes", "Notas")
	Texts.Put("wifi", "Wi-Fi")

	'=== ONBOARDING ===
	Texts.Put("onb_welcome_title", "Bem-vindo ao LockZero")
	Texts.Put("onb_welcome_text", "Lock and ZERO worries" & Chr(10) & Chr(10) & "O LockZero é seu cofre digital pessoal." & Chr(10) & Chr(10) & "• ZERO Internet - Seus dados nunca saem do dispositivo" & Chr(10) & "• ZERO Conhecimento - Nem nós sabemos sua frase" & Chr(10) & "• ZERO Recuperação - Você é o único responsável" & Chr(10) & "• Sem mensalidades - Grátis para sempre")
	Texts.Put("onb_warning_title", "⚠️ AVISO IMPORTANTE")
	Texts.Put("onb_warning_text", "LEIA COM ATENÇÃO:" & Chr(10) & Chr(10) & "1. Sua frase-senha NÃO é armazenada em nenhum lugar." & Chr(10) & Chr(10) & "2. Se você ESQUECER sua frase-senha, PERDERÁ TODOS OS SEUS DADOS." & Chr(10) & Chr(10) & "3. NÃO existe 'Esqueci minha senha'. NÃO existe recuperação." & Chr(10) & Chr(10) & "4. NINGUÉM pode ajudar você. Nem nós, nem a Google, nem ninguém." & Chr(10) & Chr(10) & "5. BACKUPS protegem contra perda do dispositivo, NÃO contra esquecer a frase-senha." & Chr(10) & Chr(10) & "💡 DICA: Use uma oração, trecho de música ou frase pessoal que você nunca vai esquecer.")
	Texts.Put("onb_understand", "Eu entendo que NÃO há recuperação e sou o único responsável")
	Texts.Put("onb_accept", "Aceitar e Continuar")
	Texts.Put("onb_setup_title", "Crie sua Frase-Senha")
	Texts.Put("onb_setup_info", "Esta frase será usada para criptografar todos os seus dados. Escolha algo que você possa lembrar, mas que seja difícil de adivinhar." & Chr(10) & Chr(10) & "Mínimo: 8 caracteres")
	Texts.Put("onb_passphrase_hint", "Digite sua frase-senha")
	Texts.Put("onb_passphrase_confirm", "Confirme sua frase-senha")
	Texts.Put("onb_create_continue", "Criar e Continuar")
	Texts.Put("onb_backup_title", "Backup Opcional")
	Texts.Put("onb_backup_text", "Você pode criar um backup agora ou depois nas configurações." & Chr(10) & Chr(10) & "Este backup será protegido pela sua frase-senha." & Chr(10) & Chr(10) & "Guarde o arquivo .lockzero em local seguro (pendrive, computador, nuvem pessoal).")
	Texts.Put("onb_create_backup", "Criar Backup Agora")
	Texts.Put("onb_skip_backup", "Pular por Agora")
	Texts.Put("onb_complete_title", "Tudo Pronto!")
	Texts.Put("onb_complete_text", "Seu LockZero está configurado e protegido." & Chr(10) & Chr(10) & "Lembre-se:" & Chr(10) & "• Sua frase-senha: NUNCA esqueça" & Chr(10) & "• Backups: Faça regularmente" & Chr(10) & "• Segurança: 100% em suas mãos" & Chr(10) & Chr(10) & "Lock and ZERO worries!" & Chr(10) & "(Tranque e ZERO preocupação!)")
	Texts.Put("onb_start", "Começar a Usar")
	Texts.Put("onb_min_chars", "Frase-senha deve ter no mínimo 8 caracteres")
	Texts.Put("onb_not_match", "As frases-senha não conferem")
	Texts.Put("onb_must_accept", "Você precisa aceitar os termos")
	Texts.Put("onb_complete_setup", "Complete a configuração inicial")

	'=== GRUPOS ===
	Texts.Put("new_group", "Novo Grupo")
	Texts.Put("edit_group", "Editar Grupo")
	Texts.Put("group_name_hint", "Nome do grupo")

	'=== SENHAS ===
	Texts.Put("password", "Senha")
	Texts.Put("username", "Usuário")
	Texts.Put("url", "URL/Site")
	Texts.Put("site_name", "Nome do site")
	Texts.Put("site_name_hint", "Ex: Google, Facebook...")
	Texts.Put("username_hint", "Email ou usuário")
	Texts.Put("password_hint", "Senha")
	Texts.Put("notes_hint", "Observações (opcional)")
	Texts.Put("favorite", "Favorito")
	Texts.Put("new_password", "Nova Senha")
	Texts.Put("add_password", "Adicionar senha")
	Texts.Put("edit_password", "Editar senha")
	Texts.Put("password_copied", "Senha copiada!")
	Texts.Put("clipboard_clear", "Clipboard limpo")
	Texts.Put("seconds", "segundos")
	Texts.Put("generate_password", "Gerar senha")
	Texts.Put("password_strength", "Força da senha")
	Texts.Put("weak", "Fraca")
	Texts.Put("medium", "Média")
	Texts.Put("strong", "Forte")
	Texts.Put("very_strong", "Muito forte")

	'=== CARTOES ===
	Texts.Put("card", "Cartão")
	Texts.Put("card_number", "Número do cartão")
	Texts.Put("card_holder", "Nome no cartão")
	Texts.Put("expiry_date", "Validade")
	Texts.Put("cvv", "CVV")
	Texts.Put("card_nickname", "Apelido do cartão")
	Texts.Put("add_card", "Adicionar cartão")
	Texts.Put("edit_card", "Editar cartão")

	'=== DOCUMENTOS ===
	Texts.Put("document", "Documento")
	Texts.Put("document_type", "Tipo de documento")
	Texts.Put("add_document", "Adicionar documento")
	Texts.Put("take_photo", "Tirar foto")
	Texts.Put("choose_photo", "Escolher da galeria")
	Texts.Put("doc_cpf", "CPF")
	Texts.Put("doc_rg", "RG")
	Texts.Put("doc_cnh", "CNH")
	Texts.Put("doc_passport", "Passaporte")
	Texts.Put("doc_other", "Outro")

	'=== CARTOES (grupo sistema) ===
	Texts.Put("card_name", "Nome")
	Texts.Put("card_brand", "Bandeira")
	Texts.Put("card_number", "Número")
	Texts.Put("card_expiry", "Validade")
	Texts.Put("card_cvv", "CVV")
	Texts.Put("card_password", "Senha")
	Texts.Put("card_holder", "Titular")
	Texts.Put("card_limit", "Limite")
	Texts.Put("clear_cards", "Limpar cartões")
	Texts.Put("clear_cards_confirm", "Excluir todos os cartões deste grupo?")
	Texts.Put("new_card", "Novo Cartão")

	'=== NOTAS ===
	Texts.Put("note", "Nota")
	Texts.Put("note_title", "Título")
	Texts.Put("note_content", "Conteúdo")
	Texts.Put("new_note", "Nova Nota")
	Texts.Put("add_note", "Adicionar nota")
	Texts.Put("edit_note", "Editar nota")

	'=== ANEXOS ===
	Texts.Put("attachments", "Anexos")
	Texts.Put("add_attachment", "Anexar arquivo")
	Texts.Put("open_file", "Abrir arquivo")
	Texts.Put("delete_attachment", "Remover anexo")
	Texts.Put("no_attachments", "Nenhum anexo")
	Texts.Put("file_not_found", "Arquivo não encontrado")
	Texts.Put("select_file", "Selecionar arquivo")
	Texts.Put("attachment_added", "Anexo adicionado")
	Texts.Put("attachment_name", "Nome do anexo")
	Texts.Put("file_exists", "Arquivo já existe")

	'=== GRUPOS DE NOTAS ===
	Texts.Put("note_groups", "Grupos de Notas")
	Texts.Put("note_group_new", "Novo Grupo")
	Texts.Put("note_group_name", "Nome do grupo")
	Texts.Put("note_group_icon", "Emoji do grupo")
	Texts.Put("note_group_icon_hint", "Toque para escolher emoji")
	Texts.Put("note_group_secure", "Grupo seguro (com cadeado)")
	Texts.Put("note_group_open", "Acesso livre")
	Texts.Put("note_group_delete", "Excluir grupo")
	Texts.Put("note_group_delete_confirm", "Excluir este grupo e todas as suas notas?")
	Texts.Put("note_group_empty", "Nenhum grupo de notas. Toque em + para criar.")
	Texts.Put("note_group_setup_phrase", "Configure a frase-senha para este grupo")
	Texts.Put("note_type_text", "Texto")
	Texts.Put("note_type_list", "Lista de tarefas")
	Texts.Put("note_type_choose", "Qual tipo de nota?")
	Texts.Put("note_add_item", "Adicionar item")
	Texts.Put("note_items_count", "%1 de %2 itens")
	Texts.Put("note_share", "Compartilhar")
	Texts.Put("note_share_confirm", "Exportar como texto aberto?")
	Texts.Put("note_share_auth", "Confirme para exportar")
	Texts.Put("note_reorder", "Segure e arraste para reordenar")
	Texts.Put("new_list", "Nova Lista")
	Texts.Put("new_text", "Novo Texto")
	Texts.Put("add_item", "Incluir Item")
	Texts.Put("title", "Título")
	Texts.Put("title_hint", "Digite o título")
	Texts.Put("item_hint", "Digite o item")
	Texts.Put("filter_items", "Filtrar itens...")
	Texts.Put("share", "Compartilhar")
	Texts.Put("share_which", "Compartilhar quais itens?")
	Texts.Put("share_all", "Todos")
	Texts.Put("share_checked", "Só marcados")
	Texts.Put("content", "Conteúdo")
	Texts.Put("content_hint", "Digite o conteúdo...")
	Texts.Put("mark_favorite", "Marcar como favorito")
	Texts.Put("confirm_delete_item", "Excluir este item?")
	Texts.Put("edit_item", "Editar item")
	Texts.Put("error_not_found", "Não encontrado")
	Texts.Put("of", "de")
	Texts.Put("items", "itens")
	Texts.Put("continue", "Continuar")

	'=== WIFI ===
	Texts.Put("wifi_name", "Nome da rede (SSID)")
	Texts.Put("wifi_password", "Senha da rede")
	Texts.Put("wifi_security", "Tipo de segurança")
	Texts.Put("add_wifi", "Adicionar rede")

	'=== GERADOR ===
	Texts.Put("generator", "Gerador")
	Texts.Put("length", "Tamanho")
	Texts.Put("uppercase", "Maiúsculas (A-Z)")
	Texts.Put("lowercase", "Minúsculas (a-z)")
	Texts.Put("numbers", "Números (0-9)")
	Texts.Put("symbols", "Símbolos (!@#$)")
	Texts.Put("generate", "Gerar")
	Texts.Put("use_password", "Usar esta senha")

	'=== CONFIGURACOES ===
	Texts.Put("settings", "Configurações")
	Texts.Put("settings_general", "Geral")
	Texts.Put("settings_security", "Segurança")
	Texts.Put("data", "Dados")
	Texts.Put("language", "Idioma")
	Texts.Put("theme", "Tema")
	Texts.Put("theme_light", "Claro")
	Texts.Put("theme_dark", "Escuro")
	Texts.Put("session_timeout", "Tempo de sessão")
	Texts.Put("clipboard_timeout", "Limpar clipboard")
	Texts.Put("biometric", "Biometria")
	Texts.Put("use_pin", "Usar PIN")
	Texts.Put("use_pin_desc", "PIN de 4-8 dígitos para abrir o app")
	Texts.Put("use_biometric_desc", "Usar impressão digital ou reconhecimento facial")
	Texts.Put("create_pin_msg", "Você será solicitado a criar um PIN de 4-8 dígitos.")
	Texts.Put("remove_pin_msg", "Deseja remover o PIN de acesso?")
	Texts.Put("biometric_enabled", "Biometria ativada")
	Texts.Put("biometric_disabled", "Biometria desativada")
	Texts.Put("pin_access", "PIN de acesso")
	Texts.Put("change_pin", "Alterar PIN")
	Texts.Put("remove_pin", "Remover PIN")

	'=== PIN/BIOMETRIA - DIALOGS ===
	Texts.Put("pin_title", "Digite o PIN")
	Texts.Put("pin_enter", "Digite seu PIN de acesso")
	Texts.Put("pin_create", "Crie um PIN de 4-8 dígitos")
	Texts.Put("pin_confirm", "Confirme o PIN")
	Texts.Put("pin_wrong", "PIN incorreto")
	Texts.Put("pin_saved", "PIN salvo com sucesso")
	Texts.Put("pin_removed", "PIN removido")
	Texts.Put("pin_mismatch", "Os PINs não coincidem")
	Texts.Put("pin_too_short", "PIN deve ter 4-8 dígitos")
	Texts.Put("pin_digits", "4-8 dígitos numéricos")
	Texts.Put("pin_current", "Digite o PIN atual")
	Texts.Put("biometric_title", "Autenticação")
	Texts.Put("biometric_prompt", "Use sua digital para continuar")
	Texts.Put("biometric_or_pin", "Ou digite seu PIN")
	Texts.Put("biometric_failed", "Falha na autenticação")
	Texts.Put("biometric_unavailable", "Biometria não disponível")
	Texts.Put("about", "Sobre")
	Texts.Put("version", "Versão")
	Texts.Put("clear_data", "Limpar todos os dados")
	Texts.Put("clear_data_desc", "Remove todas as senhas, grupos e notas")
	Texts.Put("clear_data_confirm", "ATENÇÃO: Isso irá APAGAR PERMANENTEMENTE todos os seus dados (senhas, grupos, notas). Esta ação NÃO pode ser desfeita. Deseja continuar?")
	Texts.Put("data_cleared", "Todos os dados foram apagados")
	Texts.Put("export_data", "Exportar dados")
	Texts.Put("import_data", "Importar dados")
	Texts.Put("backup", "Backup")
	Texts.Put("minute", "minuto")
	Texts.Put("minutes", "minutos")

	'=== CONFIRMACOES ===
	Texts.Put("confirm_delete", "Confirmar exclusão")
	Texts.Put("confirm_delete_msg", "Deseja realmente excluir este item?")
	Texts.Put("confirm_exit", "Deseja sair?")

	'=== ERROS ===
	Texts.Put("error_empty_field", "Preencha todos os campos")
	Texts.Put("error_invalid_data", "Dados inválidos")
	Texts.Put("error_save", "Erro ao salvar")
	Texts.Put("error_load", "Erro ao carregar")

	'=== BACKUP ===
	Texts.Put("backup_last", "Último backup:")
	Texts.Put("backup_never", "Nenhum backup realizado")
	Texts.Put("backup_export", "EXPORTAR")
	Texts.Put("backup_create", "Criar Backup Agora")
	Texts.Put("backup_create_info", "Cria um arquivo .lockzero criptografado com todos os seus dados.")
	Texts.Put("backup_import", "IMPORTAR")
	Texts.Put("backup_restore", "Restaurar Backup")
	Texts.Put("backup_restore_info", "Restaura dados de um arquivo .lockzero. Você precisará da frase usada ao criar o backup.")
	Texts.Put("backup_paste", "Colar Backup")
	Texts.Put("backup_paste_instructions", "Abra o arquivo .lockzero em um editor de texto, copie todo o conteúdo e cole aqui.")
	Texts.Put("backup_paste_hint", "Cole aqui o conteúdo do backup...")
	Texts.Put("backup_paste_empty", "Cole o conteúdo do backup")
	Texts.Put("backup_invalid", "Formato de backup inválido")
	Texts.Put("backup_verify", "VERIFICAR")
	Texts.Put("backup_test", "Testar Backup")
	Texts.Put("backup_test_info", "Verifica se o backup pode ser aberto. Não altera seus dados atuais.")
	Texts.Put("backup_tip", "DICA: Use uma oração, trecho de música ou frase que você já conhece de cor. Assim não precisa anotar!")
	Texts.Put("backup_phrase_hint", "Frase para proteger o backup")
	Texts.Put("backup_phrase_min", "Frase deve ter no mínimo 6 caracteres")
	Texts.Put("backup_success", "Backup criado com sucesso!")
	Texts.Put("backup_saved_at", "Salvo em:")
	Texts.Put("backup_error", "Erro ao criar backup")
	Texts.Put("backup_none_found", "Nenhum arquivo .lockzero encontrado")
	Texts.Put("backup_phrase_backup", "Frase do backup")
	Texts.Put("backup_enter_phrase", "Digite a frase usada ao criar o backup:")
	Texts.Put("backup_confirm_restore", "ATENÇÃO: Isso irá adicionar os dados do backup aos seus dados atuais.")
	Texts.Put("backup_continue", "Deseja continuar?")
	Texts.Put("backup_restored", "Backup restaurado!")
	Texts.Put("backup_groups", "Grupos:")
	Texts.Put("backup_entries", "Senhas:")
	Texts.Put("backup_notes", "Notas:")
	Texts.Put("backup_valid", "Backup VÁLIDO!")
	Texts.Put("backup_created_at", "Criado em:")
	Texts.Put("backup_test_ok", "Teste OK")
	Texts.Put("backup_test_failed", "Frase incorreta ou arquivo corrompido")
	Texts.Put("backup_wrong_phrase", "Frase incorreta ou arquivo corrompido")
	Texts.Put("backup_share_question", "Deseja compartilhar o arquivo de backup?")
	Texts.Put("share", "Compartilhar")
	Texts.Put("share_error", "Erro ao compartilhar")

	'=== IMPORT CSV ===
	Texts.Put("import_csv", "Importar CSV")
	Texts.Put("csv_entries_found", "entradas encontradas")
	Texts.Put("csv_selected", "Selecionadas")
	Texts.Put("csv_select_all", "Selecionar Todos")
	Texts.Put("csv_deselect_all", "Desmarcar Todos")
	Texts.Put("csv_select_group", "Selecionar Grupo")
	Texts.Put("csv_new_group", "Novo Grupo")
	Texts.Put("csv_import_btn", "Importar")
	Texts.Put("csv_imported", "entradas importadas")
	Texts.Put("csv_updated", "atualizadas")
	Texts.Put("csv_skipped", "ignoradas (incompletas)")
	Texts.Put("csv_no_entries", "Nenhuma entrada válida no CSV")
	Texts.Put("csv_no_groups", "Nenhum grupo existente")
	Texts.Put("csv_select_at_least_one", "Selecione pelo menos uma entrada")
	Texts.Put("csv_select_group_first", "Selecione ou crie um grupo primeiro")
	Texts.Put("csv_error_parse", "Erro ao ler arquivo CSV")

	'CSV Import Instructions
	Texts.Put("csv_how_to_title", "Como Importar do Chrome")
	Texts.Put("csv_how_to_1", "1. No PC: Chrome → Menu (⋮) → Senhas")
	Texts.Put("csv_how_to_2", "2. Gerenciador de senhas → Configurações (⚙)")
	Texts.Put("csv_how_to_3", "3. Exportar senhas → Download do arquivo")
	Texts.Put("csv_how_to_4", "4. Envie o CSV para o celular (WhatsApp, etc)")
	Texts.Put("csv_how_to_5", "5. Toque no arquivo → Abrir com → LockZero")
	Texts.Put("understood", "Entendi")
End Sub

Private Sub LoadEnglish
	'=== APP ===
	Texts.Put("app_name", "LockZero")
	Texts.Put("app_tagline", "Lock and ZERO worries")
	Texts.Put("app_slogan", "Store your information with ZERO worries")
	Texts.Put("free_version", "Free Version")

	'=== GENERAL ===
	Texts.Put("ok", "OK")
	Texts.Put("cancel", "Cancel")
	Texts.Put("save", "Save")
	Texts.Put("delete", "Delete")
	Texts.Put("edit", "Edit")
	Texts.Put("add", "Add")
	Texts.Put("close", "Close")
	Texts.Put("back", "Back")
	Texts.Put("next", "Next")
	Texts.Put("done", "Done")
	Texts.Put("search", "Search")
	Texts.Put("search_hint", "Search by name or URL...")
	Texts.Put("search_no_results", "No results found")
	Texts.Put("copy", "Copy")
	Texts.Put("copied", "Copied!")
	Texts.Put("show", "Show")
	Texts.Put("hide", "Hide")
	Texts.Put("view", "View")
	Texts.Put("yes", "Yes")
	Texts.Put("no", "No")
	Texts.Put("loading", "Loading...")
	Texts.Put("empty", "No items")
	Texts.Put("error", "Error")
	Texts.Put("success", "Success")
	Texts.Put("warning", "Warning")
	Texts.Put("discard", "Discard")
	Texts.Put("discard_changes", "Discard changes?")
	Texts.Put("invalid_card_number", "Invalid card number")

	'=== AUTHENTICATION ===
	Texts.Put("enter_passphrase", "Enter your secret phrase")
	Texts.Put("passphrase_hint", "Your personal phrase...")
	Texts.Put("passphrase_confirm_new", "Confirm the new phrase again")
	Texts.Put("passphrase_mismatch", "Phrases do not match")
	Texts.Put("passphrase_min_8", "Phrase must have at least 8 characters")
	Texts.Put("passphrase_too_short", "Phrase too short")
	Texts.Put("confirm", "Confirm")
	Texts.Put("unlock", "Unlock")
	Texts.Put("use_biometric", "Use biometric")
	Texts.Put("wrong_passphrase", "Wrong phrase")
	Texts.Put("session_expired", "Session expired")
	Texts.Put("session_remaining", "Session expires in")
	Texts.Put("wait_timeout", "Wait")
	Texts.Put("attempts", "attempts")
	Texts.Put("failed_attempts", "failed attempts")
	Texts.Put("lock", "Lock")
	Texts.Put("lock_confirm_msg", "Lock the session now?")
	Texts.Put("locked", "Session locked")
	Texts.Put("session_active", "Session active")

	'=== PASSPHRASE MODE ===
	Texts.Put("passphrase_mode", "Passphrase mode")
	Texts.Put("single_passphrase", "Single passphrase")
	Texts.Put("single_passphrase_desc", "Use the same passphrase for all categories")
	Texts.Put("multi_passphrase", "Per category passphrase")
	Texts.Put("multi_passphrase_desc", "Each category can have its own passphrase")
	Texts.Put("single_passphrase_warning", "Single passphrase mode active. To use different passphrases per group, change in Settings.")

	'=== CATEGORIES ===
	Texts.Put("passwords", "Passwords")
	Texts.Put("cards", "Cards")
	Texts.Put("documents", "Documents")
	Texts.Put("notes", "Notes")
	Texts.Put("wifi", "Wi-Fi")

	'=== GROUPS ===
	Texts.Put("new_group", "New Group")
	Texts.Put("edit_group", "Edit Group")
	Texts.Put("group_name_hint", "Group name")

	'=== PASSWORDS ===
	Texts.Put("password", "Password")
	Texts.Put("username", "Username")
	Texts.Put("url", "URL/Website")
	Texts.Put("site_name", "Site name")
	Texts.Put("site_name_hint", "Ex: Google, Facebook...")
	Texts.Put("username_hint", "Email or username")
	Texts.Put("password_hint", "Password")
	Texts.Put("notes_hint", "Notes (optional)")
	Texts.Put("favorite", "Favorite")
	Texts.Put("new_password", "New Password")
	Texts.Put("add_password", "Add password")
	Texts.Put("edit_password", "Edit password")
	Texts.Put("password_copied", "Password copied!")
	Texts.Put("clipboard_clear", "Clipboard clears in")
	Texts.Put("seconds", "seconds")
	Texts.Put("generate_password", "Generate password")
	Texts.Put("password_strength", "Password strength")
	Texts.Put("weak", "Weak")
	Texts.Put("medium", "Medium")
	Texts.Put("strong", "Strong")
	Texts.Put("very_strong", "Very strong")

	'=== CARDS ===
	Texts.Put("card", "Card")
	Texts.Put("card_number", "Card number")
	Texts.Put("card_holder", "Cardholder name")
	Texts.Put("expiry_date", "Expiry date")
	Texts.Put("cvv", "CVV")
	Texts.Put("card_nickname", "Card nickname")
	Texts.Put("add_card", "Add card")
	Texts.Put("edit_card", "Edit card")

	'=== DOCUMENTS ===
	Texts.Put("document", "Document")
	Texts.Put("document_type", "Document type")
	Texts.Put("add_document", "Add document")
	Texts.Put("take_photo", "Take photo")
	Texts.Put("choose_photo", "Choose from gallery")
	Texts.Put("doc_cpf", "CPF")
	Texts.Put("doc_rg", "RG")
	Texts.Put("doc_cnh", "Driver License")
	Texts.Put("doc_passport", "Passport")
	Texts.Put("doc_other", "Other")

	'=== CARDS (system group) ===
	Texts.Put("card_name", "Name")
	Texts.Put("card_brand", "Brand")
	Texts.Put("card_number", "Number")
	Texts.Put("card_expiry", "Expiry")
	Texts.Put("card_cvv", "CVV")
	Texts.Put("card_password", "Password")
	Texts.Put("card_holder", "Holder")
	Texts.Put("card_limit", "Limit")
	Texts.Put("clear_cards", "Clear cards")
	Texts.Put("clear_cards_confirm", "Delete all cards from this group?")
	Texts.Put("new_card", "New Card")

	'=== NOTES ===
	Texts.Put("note", "Note")
	Texts.Put("note_title", "Title")
	Texts.Put("note_content", "Content")
	Texts.Put("new_note", "New Note")
	Texts.Put("add_note", "Add note")
	Texts.Put("edit_note", "Edit note")

	'=== ATTACHMENTS ===
	Texts.Put("attachments", "Attachments")
	Texts.Put("add_attachment", "Attach file")
	Texts.Put("open_file", "Open file")
	Texts.Put("delete_attachment", "Remove attachment")
	Texts.Put("no_attachments", "No attachments")
	Texts.Put("file_not_found", "File not found")
	Texts.Put("select_file", "Select file")
	Texts.Put("attachment_added", "Attachment added")
	Texts.Put("attachment_name", "Attachment name")
	Texts.Put("file_exists", "File already exists")

	'=== NOTE GROUPS ===
	Texts.Put("note_groups", "Note Groups")
	Texts.Put("note_group_new", "New Group")
	Texts.Put("note_group_name", "Group name")
	Texts.Put("note_group_icon", "Group emoji")
	Texts.Put("note_group_icon_hint", "Tap to choose emoji")
	Texts.Put("note_group_secure", "Secure group (with lock)")
	Texts.Put("note_group_open", "Open access")
	Texts.Put("note_group_delete", "Delete group")
	Texts.Put("note_group_delete_confirm", "Delete this group and all its notes?")
	Texts.Put("note_group_empty", "No note groups. Tap + to create.")
	Texts.Put("note_group_setup_phrase", "Set up passphrase for this group")
	Texts.Put("note_type_text", "Text")
	Texts.Put("note_type_list", "Checklist")
	Texts.Put("note_type_choose", "What type of note?")
	Texts.Put("note_add_item", "Add item")
	Texts.Put("note_items_count", "%1 of %2 items")
	Texts.Put("note_share", "Share")
	Texts.Put("note_share_confirm", "Export as plain text?")
	Texts.Put("note_share_auth", "Confirm to export")
	Texts.Put("note_reorder", "Hold and drag to reorder")
	Texts.Put("new_list", "New List")
	Texts.Put("new_text", "New Text")
	Texts.Put("add_item", "Add Item")
	Texts.Put("title", "Title")
	Texts.Put("title_hint", "Enter the title")
	Texts.Put("item_hint", "Enter the item")
	Texts.Put("filter_items", "Filter items...")
	Texts.Put("share", "Share")
	Texts.Put("share_which", "Share which items?")
	Texts.Put("share_all", "All")
	Texts.Put("share_checked", "Only checked")
	Texts.Put("content", "Content")
	Texts.Put("content_hint", "Enter the content...")
	Texts.Put("mark_favorite", "Mark as favorite")
	Texts.Put("confirm_delete_item", "Delete this item?")
	Texts.Put("edit_item", "Edit item")
	Texts.Put("error_not_found", "Not found")
	Texts.Put("of", "of")
	Texts.Put("items", "items")
	Texts.Put("continue", "Continue")

	'=== WIFI ===
	Texts.Put("wifi_name", "Network name (SSID)")
	Texts.Put("wifi_password", "Network password")
	Texts.Put("wifi_security", "Security type")
	Texts.Put("add_wifi", "Add network")

	'=== GENERATOR ===
	Texts.Put("generator", "Generator")
	Texts.Put("length", "Length")
	Texts.Put("uppercase", "Uppercase (A-Z)")
	Texts.Put("lowercase", "Lowercase (a-z)")
	Texts.Put("numbers", "Numbers (0-9)")
	Texts.Put("symbols", "Symbols (!@#$)")
	Texts.Put("generate", "Generate")
	Texts.Put("use_password", "Use this password")

	'=== SETTINGS ===
	Texts.Put("settings", "Settings")
	Texts.Put("settings_general", "General")
	Texts.Put("settings_security", "Security")
	Texts.Put("data", "Data")
	Texts.Put("language", "Language")
	Texts.Put("theme", "Theme")
	Texts.Put("theme_light", "Light")
	Texts.Put("theme_dark", "Dark")
	Texts.Put("session_timeout", "Session timeout")
	Texts.Put("clipboard_timeout", "Clear clipboard")
	Texts.Put("biometric", "Biometric")
	Texts.Put("use_pin", "Use PIN")
	Texts.Put("use_pin_desc", "4-8 digit PIN to open the app")
	Texts.Put("use_biometric_desc", "Use fingerprint or face recognition")
	Texts.Put("create_pin_msg", "You will be asked to create a 4-8 digit PIN.")
	Texts.Put("remove_pin_msg", "Do you want to remove the access PIN?")
	Texts.Put("biometric_enabled", "Biometric enabled")
	Texts.Put("biometric_disabled", "Biometric disabled")
	Texts.Put("pin_access", "PIN access")
	Texts.Put("change_pin", "Change PIN")
	Texts.Put("remove_pin", "Remove PIN")

	'=== PIN/BIOMETRIC - DIALOGS ===
	Texts.Put("pin_title", "Enter PIN")
	Texts.Put("pin_enter", "Enter your access PIN")
	Texts.Put("pin_create", "Create a 4-8 digit PIN")
	Texts.Put("pin_confirm", "Confirm PIN")
	Texts.Put("pin_wrong", "Wrong PIN")
	Texts.Put("pin_saved", "PIN saved successfully")
	Texts.Put("pin_removed", "PIN removed")
	Texts.Put("pin_mismatch", "PINs do not match")
	Texts.Put("pin_too_short", "PIN must be 4-8 digits")
	Texts.Put("pin_digits", "4-8 numeric digits")
	Texts.Put("pin_current", "Enter current PIN")
	Texts.Put("biometric_title", "Authentication")
	Texts.Put("biometric_prompt", "Use your fingerprint to continue")
	Texts.Put("biometric_or_pin", "Or enter your PIN")
	Texts.Put("biometric_failed", "Authentication failed")
	Texts.Put("biometric_unavailable", "Biometric not available")
	Texts.Put("about", "About")
	Texts.Put("version", "Version")
	Texts.Put("clear_data", "Clear all data")
	Texts.Put("clear_data_desc", "Remove all passwords, groups and notes")
	Texts.Put("clear_data_confirm", "WARNING: This will PERMANENTLY DELETE all your data (passwords, groups, notes). This action CANNOT be undone. Do you want to continue?")
	Texts.Put("data_cleared", "All data has been deleted")
	Texts.Put("export_data", "Export data")
	Texts.Put("import_data", "Import data")
	Texts.Put("backup", "Backup")
	Texts.Put("minute", "minute")
	Texts.Put("minutes", "minutes")

	'=== CONFIRMATIONS ===
	Texts.Put("confirm_delete", "Confirm delete")
	Texts.Put("confirm_delete_msg", "Do you really want to delete this item?")
	Texts.Put("confirm_exit", "Do you want to exit?")

	'=== ONBOARDING ===
	Texts.Put("onb_welcome_title", "Welcome to LockZero")
	Texts.Put("onb_welcome_text", "Lock and ZERO worries" & Chr(10) & Chr(10) & "LockZero is your personal digital vault." & Chr(10) & Chr(10) & "• ZERO Internet - Your data never leaves the device" & Chr(10) & "• ZERO Knowledge - Not even we know your phrase" & Chr(10) & "• ZERO Recovery - You are solely responsible" & Chr(10) & "• ZERO Subscription - One-time payment or free")
	Texts.Put("onb_warning_title", "⚠️ IMPORTANT WARNING")
	Texts.Put("onb_warning_text", "READ CAREFULLY:" & Chr(10) & Chr(10) & "1. Your passphrase is NOT stored anywhere." & Chr(10) & Chr(10) & "2. If you FORGET your passphrase, you WILL LOSE ALL YOUR DATA." & Chr(10) & Chr(10) & "3. There is NO 'Forgot password'. There is NO recovery." & Chr(10) & Chr(10) & "4. NOBODY can help you. Not us, not Google, nobody." & Chr(10) & Chr(10) & "5. BACKUPS protect against device loss, NOT against forgetting your passphrase." & Chr(10) & Chr(10) & "💡 TIP: Use a prayer, song lyric, or personal phrase you will never forget.")
	Texts.Put("onb_understand", "I understand there is NO recovery and I am solely responsible")
	Texts.Put("onb_accept", "Accept and Continue")
	Texts.Put("onb_setup_title", "Create your Passphrase")
	Texts.Put("onb_setup_info", "This phrase will be used to encrypt all your data. Choose something you can remember, but that is hard to guess." & Chr(10) & Chr(10) & "Minimum: 8 characters")
	Texts.Put("onb_passphrase_hint", "Enter your passphrase")
	Texts.Put("onb_passphrase_confirm", "Confirm your passphrase")
	Texts.Put("onb_create_continue", "Create and Continue")
	Texts.Put("onb_backup_title", "Optional Backup")
	Texts.Put("onb_backup_text", "You can create a backup now or later in settings." & Chr(10) & Chr(10) & "This backup will be protected by your passphrase." & Chr(10) & Chr(10) & "Store the .lockzero file in a safe place (USB drive, computer, personal cloud).")
	Texts.Put("onb_create_backup", "Create Backup Now")
	Texts.Put("onb_skip_backup", "Skip for Now")
	Texts.Put("onb_complete_title", "All Set!")
	Texts.Put("onb_complete_text", "Your LockZero is configured and protected." & Chr(10) & Chr(10) & "Remember:" & Chr(10) & "• Your passphrase: NEVER forget" & Chr(10) & "• Backups: Do them regularly" & Chr(10) & "• Security: 100% in your hands" & Chr(10) & Chr(10) & "Lock and ZERO worries!")
	Texts.Put("onb_start", "Start Using")
	Texts.Put("onb_min_chars", "Passphrase must have at least 8 characters")
	Texts.Put("onb_not_match", "Passphrases do not match")
	Texts.Put("onb_must_accept", "You need to accept the terms")
	Texts.Put("onb_complete_setup", "Complete the initial setup")

	'=== ERRORS ===
	Texts.Put("error_empty_field", "Please fill all fields")
	Texts.Put("error_invalid_data", "Invalid data")
	Texts.Put("error_save", "Error saving")
	Texts.Put("error_load", "Error loading")

	'=== BACKUP ===
	Texts.Put("backup_last", "Last backup:")
	Texts.Put("backup_never", "No backup made")
	Texts.Put("backup_export", "EXPORT")
	Texts.Put("backup_create", "Create Backup Now")
	Texts.Put("backup_create_info", "Creates an encrypted .lockzero file with all your data.")
	Texts.Put("backup_import", "IMPORT")
	Texts.Put("backup_restore", "Restore Backup")
	Texts.Put("backup_restore_info", "Restores data from a .lockzero file. You will need the phrase used when creating the backup.")
	Texts.Put("backup_paste", "Paste Backup")
	Texts.Put("backup_paste_instructions", "Open the .lockzero file in a text editor, copy all content and paste here.")
	Texts.Put("backup_paste_hint", "Paste the backup content here...")
	Texts.Put("backup_paste_empty", "Paste the backup content")
	Texts.Put("backup_invalid", "Invalid backup format")
	Texts.Put("backup_verify", "VERIFY")
	Texts.Put("backup_test", "Test Backup")
	Texts.Put("backup_test_info", "Checks if the backup can be opened. Does not change your current data.")
	Texts.Put("backup_tip", "TIP: Use a prayer, song lyric, or phrase you already know by heart. No need to write it down!")
	Texts.Put("backup_phrase_hint", "Phrase to protect the backup")
	Texts.Put("backup_phrase_min", "Phrase must have at least 6 characters")
	Texts.Put("backup_success", "Backup created successfully!")
	Texts.Put("backup_saved_at", "Saved at:")
	Texts.Put("backup_error", "Error creating backup")
	Texts.Put("backup_none_found", "No .lockzero file found")
	Texts.Put("backup_phrase_backup", "Backup phrase")
	Texts.Put("backup_enter_phrase", "Enter the phrase used when creating the backup:")
	Texts.Put("backup_confirm_restore", "WARNING: This will add the backup data to your current data.")
	Texts.Put("backup_continue", "Do you want to continue?")
	Texts.Put("backup_restored", "Backup restored!")
	Texts.Put("backup_groups", "Groups:")
	Texts.Put("backup_entries", "Passwords:")
	Texts.Put("backup_notes", "Notes:")
	Texts.Put("backup_valid", "Backup VALID!")
	Texts.Put("backup_created_at", "Created at:")
	Texts.Put("backup_test_ok", "Test OK")
	Texts.Put("backup_test_failed", "Wrong phrase or corrupted file")
	Texts.Put("backup_wrong_phrase", "Wrong phrase or corrupted file")
	Texts.Put("backup_share_question", "Share the backup file?")
	Texts.Put("share", "Share")
	Texts.Put("share_error", "Error sharing")

	'=== IMPORT CSV ===
	Texts.Put("import_csv", "Import CSV")
	Texts.Put("csv_entries_found", "entries found")
	Texts.Put("csv_selected", "Selected")
	Texts.Put("csv_select_all", "Select All")
	Texts.Put("csv_deselect_all", "Deselect All")
	Texts.Put("csv_select_group", "Select Group")
	Texts.Put("csv_new_group", "New Group")
	Texts.Put("csv_import_btn", "Import")
	Texts.Put("csv_imported", "entries imported")
	Texts.Put("csv_updated", "updated")
	Texts.Put("csv_skipped", "skipped (incomplete)")
	Texts.Put("csv_no_entries", "No valid entries in CSV")
	Texts.Put("csv_no_groups", "No existing groups")
	Texts.Put("csv_select_at_least_one", "Select at least one entry")
	Texts.Put("csv_select_group_first", "Select or create a group first")
	Texts.Put("csv_error_parse", "Error reading CSV file")

	'CSV Import Instructions
	Texts.Put("csv_how_to_title", "How to Import from Chrome")
	Texts.Put("csv_how_to_1", "1. On PC: Chrome → Menu (⋮) → Passwords")
	Texts.Put("csv_how_to_2", "2. Password Manager → Settings (⚙)")
	Texts.Put("csv_how_to_3", "3. Export passwords → Download file")
	Texts.Put("csv_how_to_4", "4. Send CSV to your phone (WhatsApp, etc)")
	Texts.Put("csv_how_to_5", "5. Tap file → Open with → LockZero")
	Texts.Put("understood", "Got it")
End Sub

Private Sub LoadSpanish
	'=== APP ===
	Texts.Put("app_name", "LockZero")
	Texts.Put("app_tagline", "Lock and ZERO worries")
	Texts.Put("app_slogan", "Guarda tu información con CERO preocupaciones")
	Texts.Put("free_version", "Versión Gratuita")

	'=== GENERAL ===
	Texts.Put("ok", "OK")
	Texts.Put("cancel", "Cancelar")
	Texts.Put("save", "Guardar")
	Texts.Put("delete", "Eliminar")
	Texts.Put("edit", "Editar")
	Texts.Put("add", "Agregar")
	Texts.Put("close", "Cerrar")
	Texts.Put("back", "Volver")
	Texts.Put("next", "Siguiente")
	Texts.Put("continue", "Continuar")
	Texts.Put("done", "Listo")
	Texts.Put("search", "Buscar")
	Texts.Put("search_hint", "Buscar por nombre o URL...")
	Texts.Put("search_no_results", "No se encontraron resultados")
	Texts.Put("copy", "Copiar")
	Texts.Put("copied", "¡Copiado!")
	Texts.Put("show", "Mostrar")
	Texts.Put("hide", "Ocultar")
	Texts.Put("view", "Ver")
	Texts.Put("yes", "Sí")
	Texts.Put("no", "No")
	Texts.Put("loading", "Cargando...")
	Texts.Put("empty", "Sin elementos")
	Texts.Put("error", "Error")
	Texts.Put("success", "Éxito")
	Texts.Put("warning", "Aviso")
	Texts.Put("discard", "Descartar")
	Texts.Put("discard_changes", "¿Descartar cambios?")
	Texts.Put("invalid_card_number", "Número de tarjeta inválido")

	'=== AUTHENTICATION ===
	Texts.Put("enter_passphrase", "Ingresa tu frase secreta")
	Texts.Put("passphrase_hint", "Tu frase personal...")
	Texts.Put("passphrase_confirm_new", "Confirma nuevamente la frase nueva")
	Texts.Put("passphrase_mismatch", "Las frases no coinciden")
	Texts.Put("passphrase_min_8", "La frase debe tener mínimo 8 caracteres")
	Texts.Put("passphrase_too_short", "Frase muy corta")
	Texts.Put("confirm", "Confirmar")
	Texts.Put("unlock", "Desbloquear")
	Texts.Put("use_biometric", "Usar biometría")
	Texts.Put("wrong_passphrase", "Frase incorrecta")
	Texts.Put("session_expired", "Sesión expirada")
	Texts.Put("session_remaining", "La sesión expira en")
	Texts.Put("wait_timeout", "Espera")
	Texts.Put("attempts", "intentos")
	Texts.Put("failed_attempts", "intentos fallidos")
	Texts.Put("lock", "Bloquear")
	Texts.Put("lock_confirm_msg", "¿Bloquear la sesión ahora?")
	Texts.Put("locked", "Sesión bloqueada")
	Texts.Put("session_active", "Sesión activa")

	'=== PASSPHRASE MODE ===
	Texts.Put("passphrase_mode", "Modo de frase-contraseña")
	Texts.Put("single_passphrase", "Frase única")
	Texts.Put("single_passphrase_desc", "Usar la misma frase para todas las categorías")
	Texts.Put("multi_passphrase", "Frase por categoría")
	Texts.Put("multi_passphrase_desc", "Cada categoría puede tener su propia frase")
	Texts.Put("single_passphrase_warning", "Modo de frase única activo. Para usar frases diferentes por grupo, cambia en Configuración.")

	'=== CATEGORIES ===
	Texts.Put("passwords", "Contraseñas")
	Texts.Put("cards", "Tarjetas")
	Texts.Put("documents", "Documentos")
	Texts.Put("notes", "Notas")
	Texts.Put("wifi", "Wi-Fi")

	'=== GROUPS ===
	Texts.Put("new_group", "Nuevo Grupo")
	Texts.Put("edit_group", "Editar Grupo")
	Texts.Put("group_name_hint", "Nombre del grupo")

	'=== PASSWORDS ===
	Texts.Put("password", "Contraseña")
	Texts.Put("username", "Usuario")
	Texts.Put("url", "URL/Sitio")
	Texts.Put("site_name", "Nombre del sitio")
	Texts.Put("site_name_hint", "Ej: Google, Facebook...")
	Texts.Put("username_hint", "Email o usuario")
	Texts.Put("password_hint", "Contraseña")
	Texts.Put("notes_hint", "Notas (opcional)")
	Texts.Put("favorite", "Favorito")
	Texts.Put("new_password", "Nueva Contraseña")
	Texts.Put("add_password", "Agregar contraseña")
	Texts.Put("edit_password", "Editar contraseña")
	Texts.Put("password_copied", "¡Contraseña copiada!")
	Texts.Put("clipboard_clear", "Portapapeles limpio")
	Texts.Put("seconds", "segundos")
	Texts.Put("generate_password", "Generar contraseña")
	Texts.Put("password_strength", "Fortaleza")
	Texts.Put("weak", "Débil")
	Texts.Put("medium", "Media")
	Texts.Put("strong", "Fuerte")
	Texts.Put("very_strong", "Muy fuerte")

	'=== CARDS ===
	Texts.Put("card", "Tarjeta")
	Texts.Put("card_number", "Número de tarjeta")
	Texts.Put("card_holder", "Nombre en la tarjeta")
	Texts.Put("expiry_date", "Fecha de vencimiento")
	Texts.Put("cvv", "CVV")
	Texts.Put("card_nickname", "Apodo de la tarjeta")
	Texts.Put("add_card", "Agregar tarjeta")
	Texts.Put("edit_card", "Editar tarjeta")

	'=== DOCUMENTS ===
	Texts.Put("document", "Documento")
	Texts.Put("document_type", "Tipo de documento")
	Texts.Put("add_document", "Agregar documento")
	Texts.Put("take_photo", "Tomar foto")
	Texts.Put("choose_photo", "Elegir de galería")
	Texts.Put("doc_cpf", "CPF")
	Texts.Put("doc_rg", "DNI")
	Texts.Put("doc_cnh", "Licencia de conducir")
	Texts.Put("doc_passport", "Pasaporte")
	Texts.Put("doc_other", "Otro")

	'=== CARDS (system group) ===
	Texts.Put("card_name", "Nombre")
	Texts.Put("card_brand", "Marca")
	Texts.Put("card_expiry", "Vencimiento")
	Texts.Put("card_cvv", "CVV")
	Texts.Put("card_password", "Contraseña")
	Texts.Put("card_limit", "Límite")
	Texts.Put("clear_cards", "Limpiar tarjetas")
	Texts.Put("clear_cards_confirm", "¿Eliminar todas las tarjetas de este grupo?")
	Texts.Put("new_card", "Nueva Tarjeta")

	'=== NOTES ===
	Texts.Put("note", "Nota")
	Texts.Put("note_title", "Título")
	Texts.Put("note_content", "Contenido")
	Texts.Put("new_note", "Nueva Nota")
	Texts.Put("add_note", "Agregar nota")
	Texts.Put("edit_note", "Editar nota")

	'=== ATTACHMENTS ===
	Texts.Put("attachments", "Adjuntos")
	Texts.Put("add_attachment", "Adjuntar archivo")
	Texts.Put("open_file", "Abrir archivo")
	Texts.Put("delete_attachment", "Eliminar adjunto")
	Texts.Put("no_attachments", "Sin adjuntos")
	Texts.Put("file_not_found", "Archivo no encontrado")
	Texts.Put("select_file", "Seleccionar archivo")
	Texts.Put("attachment_added", "Adjunto agregado")
	Texts.Put("attachment_name", "Nombre del adjunto")
	Texts.Put("file_exists", "El archivo ya existe")

	'=== NOTE GROUPS ===
	Texts.Put("note_groups", "Grupos de Notas")
	Texts.Put("note_group_new", "Nuevo Grupo")
	Texts.Put("note_group_name", "Nombre del grupo")
	Texts.Put("note_group_icon", "Emoji del grupo")
	Texts.Put("note_group_icon_hint", "Toca para elegir emoji")
	Texts.Put("note_group_secure", "Grupo seguro (con candado)")
	Texts.Put("note_group_open", "Acceso libre")
	Texts.Put("note_group_delete", "Eliminar grupo")
	Texts.Put("note_group_delete_confirm", "¿Eliminar este grupo y todas sus notas?")
	Texts.Put("note_group_empty", "Sin grupos de notas. Toca + para crear.")
	Texts.Put("note_group_setup_phrase", "Configura la frase-contraseña para este grupo")
	Texts.Put("note_type_text", "Texto")
	Texts.Put("note_type_list", "Lista de tareas")
	Texts.Put("note_type_choose", "¿Qué tipo de nota?")
	Texts.Put("note_add_item", "Agregar elemento")
	Texts.Put("note_items_count", "%1 de %2 elementos")
	Texts.Put("note_share", "Compartir")
	Texts.Put("note_share_confirm", "¿Exportar como texto plano?")
	Texts.Put("note_share_auth", "Confirma para exportar")
	Texts.Put("note_reorder", "Mantén presionado y arrastra para reordenar")
	Texts.Put("new_list", "Nueva Lista")
	Texts.Put("new_text", "Nuevo Texto")
	Texts.Put("add_item", "Agregar Elemento")
	Texts.Put("title", "Título")
	Texts.Put("title_hint", "Ingresa el título")
	Texts.Put("item_hint", "Ingresa el elemento")
	Texts.Put("filter_items", "Filtrar elementos...")
	Texts.Put("share", "Compartir")
	Texts.Put("share_which", "¿Compartir cuáles elementos?")
	Texts.Put("share_all", "Todos")
	Texts.Put("share_checked", "Solo marcados")
	Texts.Put("content", "Contenido")
	Texts.Put("content_hint", "Ingresa el contenido...")
	Texts.Put("mark_favorite", "Marcar como favorito")
	Texts.Put("confirm_delete_item", "¿Eliminar este elemento?")
	Texts.Put("edit_item", "Editar elemento")
	Texts.Put("error_not_found", "No encontrado")
	Texts.Put("of", "de")
	Texts.Put("items", "elementos")

	'=== WIFI ===
	Texts.Put("wifi_name", "Nombre de red (SSID)")
	Texts.Put("wifi_password", "Contraseña de red")
	Texts.Put("wifi_security", "Tipo de seguridad")
	Texts.Put("add_wifi", "Agregar red")

	'=== GENERATOR ===
	Texts.Put("generator", "Generador")
	Texts.Put("length", "Longitud")
	Texts.Put("uppercase", "Mayúsculas (A-Z)")
	Texts.Put("lowercase", "Minúsculas (a-z)")
	Texts.Put("numbers", "Números (0-9)")
	Texts.Put("symbols", "Símbolos (!@#$)")
	Texts.Put("generate", "Generar")
	Texts.Put("use_password", "Usar esta contraseña")

	'=== SETTINGS ===
	Texts.Put("settings", "Configuración")
	Texts.Put("settings_general", "General")
	Texts.Put("settings_security", "Seguridad")
	Texts.Put("data", "Datos")
	Texts.Put("language", "Idioma")
	Texts.Put("theme", "Tema")
	Texts.Put("theme_light", "Claro")
	Texts.Put("theme_dark", "Oscuro")
	Texts.Put("session_timeout", "Tiempo de sesión")
	Texts.Put("clipboard_timeout", "Limpiar portapapeles")
	Texts.Put("biometric", "Biometría")
	Texts.Put("use_pin", "Usar PIN")
	Texts.Put("use_pin_desc", "PIN de 4-8 dígitos para abrir la app")
	Texts.Put("use_biometric_desc", "Usar huella digital o reconocimiento facial")
	Texts.Put("create_pin_msg", "Se te pedirá crear un PIN de 4-8 dígitos.")
	Texts.Put("remove_pin_msg", "¿Deseas eliminar el PIN de acceso?")
	Texts.Put("biometric_enabled", "Biometría activada")
	Texts.Put("biometric_disabled", "Biometría desactivada")
	Texts.Put("pin_access", "PIN de acceso")
	Texts.Put("change_pin", "Cambiar PIN")
	Texts.Put("remove_pin", "Eliminar PIN")

	'=== PIN/BIOMETRIC - DIALOGS ===
	Texts.Put("pin_title", "Ingresa el PIN")
	Texts.Put("pin_enter", "Ingresa tu PIN de acceso")
	Texts.Put("pin_create", "Crea un PIN de 4-8 dígitos")
	Texts.Put("pin_confirm", "Confirma el PIN")
	Texts.Put("pin_wrong", "PIN incorrecto")
	Texts.Put("pin_saved", "PIN guardado exitosamente")
	Texts.Put("pin_removed", "PIN eliminado")
	Texts.Put("pin_mismatch", "Los PINs no coinciden")
	Texts.Put("pin_too_short", "El PIN debe tener 4-8 dígitos")
	Texts.Put("pin_digits", "4-8 dígitos numéricos")
	Texts.Put("pin_current", "Ingresa el PIN actual")
	Texts.Put("biometric_title", "Autenticación")
	Texts.Put("biometric_prompt", "Usa tu huella para continuar")
	Texts.Put("biometric_or_pin", "O ingresa tu PIN")
	Texts.Put("biometric_failed", "Fallo en la autenticación")
	Texts.Put("biometric_unavailable", "Biometría no disponible")
	Texts.Put("about", "Acerca de")
	Texts.Put("version", "Versión")
	Texts.Put("clear_data", "Borrar todos los datos")
	Texts.Put("clear_data_desc", "Elimina todas las contraseñas, grupos y notas")
	Texts.Put("clear_data_confirm", "ATENCIÓN: Esto ELIMINARÁ PERMANENTEMENTE todos tus datos (contraseñas, grupos, notas). Esta acción NO puede deshacerse. ¿Deseas continuar?")
	Texts.Put("data_cleared", "Todos los datos han sido eliminados")
	Texts.Put("export_data", "Exportar datos")
	Texts.Put("import_data", "Importar datos")
	Texts.Put("backup", "Respaldo")
	Texts.Put("minute", "minuto")
	Texts.Put("minutes", "minutos")

	'=== CONFIRMATIONS ===
	Texts.Put("confirm_delete", "Confirmar eliminación")
	Texts.Put("confirm_delete_msg", "¿Realmente deseas eliminar este elemento?")
	Texts.Put("confirm_exit", "¿Deseas salir?")

	'=== ONBOARDING ===
	Texts.Put("onb_welcome_title", "Bienvenido a LockZero")
	Texts.Put("onb_welcome_text", "Lock and ZERO worries" & Chr(10) & Chr(10) & "LockZero es tu bóveda digital personal." & Chr(10) & Chr(10) & "• CERO Internet - Tus datos nunca salen del dispositivo" & Chr(10) & "• CERO Conocimiento - Ni nosotros sabemos tu frase" & Chr(10) & "• CERO Recuperación - Tú eres el único responsable" & Chr(10) & "• Sin mensualidades - Gratis para siempre")
	Texts.Put("onb_warning_title", "⚠️ AVISO IMPORTANTE")
	Texts.Put("onb_warning_text", "LEE CON ATENCIÓN:" & Chr(10) & Chr(10) & "1. Tu frase-contraseña NO se almacena en ningún lugar." & Chr(10) & Chr(10) & "2. Si OLVIDAS tu frase-contraseña, PERDERÁS TODOS TUS DATOS." & Chr(10) & Chr(10) & "3. NO existe 'Olvidé mi contraseña'. NO hay recuperación." & Chr(10) & Chr(10) & "4. NADIE puede ayudarte. Ni nosotros, ni Google, nadie." & Chr(10) & Chr(10) & "5. Los RESPALDOS protegen contra pérdida del dispositivo, NO contra olvidar la frase." & Chr(10) & Chr(10) & "💡 CONSEJO: Usa una oración, fragmento de canción o frase personal que nunca olvidarás.")
	Texts.Put("onb_understand", "Entiendo que NO hay recuperación y soy el único responsable")
	Texts.Put("onb_accept", "Aceptar y Continuar")
	Texts.Put("onb_setup_title", "Crea tu Frase-Contraseña")
	Texts.Put("onb_setup_info", "Esta frase se usará para encriptar todos tus datos. Elige algo que puedas recordar, pero que sea difícil de adivinar." & Chr(10) & Chr(10) & "Mínimo: 8 caracteres")
	Texts.Put("onb_passphrase_hint", "Ingresa tu frase-contraseña")
	Texts.Put("onb_passphrase_confirm", "Confirma tu frase-contraseña")
	Texts.Put("onb_create_continue", "Crear y Continuar")
	Texts.Put("onb_backup_title", "Respaldo Opcional")
	Texts.Put("onb_backup_text", "Puedes crear un respaldo ahora o después en configuración." & Chr(10) & Chr(10) & "Este respaldo estará protegido por tu frase-contraseña." & Chr(10) & Chr(10) & "Guarda el archivo .lockzero en un lugar seguro (USB, computadora, nube personal).")
	Texts.Put("onb_create_backup", "Crear Respaldo Ahora")
	Texts.Put("onb_skip_backup", "Saltar por Ahora")
	Texts.Put("onb_complete_title", "¡Todo Listo!")
	Texts.Put("onb_complete_text", "Tu LockZero está configurado y protegido." & Chr(10) & Chr(10) & "Recuerda:" & Chr(10) & "• Tu frase-contraseña: NUNCA la olvides" & Chr(10) & "• Respaldos: Hazlos regularmente" & Chr(10) & "• Seguridad: 100% en tus manos" & Chr(10) & Chr(10) & "Lock and ZERO worries!" & Chr(10) & "(¡Bloquea y CERO preocupaciones!)")
	Texts.Put("onb_start", "Comenzar a Usar")
	Texts.Put("onb_min_chars", "La frase debe tener mínimo 8 caracteres")
	Texts.Put("onb_not_match", "Las frases no coinciden")
	Texts.Put("onb_must_accept", "Debes aceptar los términos")
	Texts.Put("onb_complete_setup", "Completa la configuración inicial")

	'=== ERRORS ===
	Texts.Put("error_empty_field", "Completa todos los campos")
	Texts.Put("error_invalid_data", "Datos inválidos")
	Texts.Put("error_save", "Error al guardar")
	Texts.Put("error_load", "Error al cargar")

	'=== BACKUP ===
	Texts.Put("backup_last", "Último respaldo:")
	Texts.Put("backup_never", "Sin respaldos realizados")
	Texts.Put("backup_export", "EXPORTAR")
	Texts.Put("backup_create", "Crear Respaldo Ahora")
	Texts.Put("backup_create_info", "Crea un archivo .lockzero encriptado con todos tus datos.")
	Texts.Put("backup_import", "IMPORTAR")
	Texts.Put("backup_restore", "Restaurar Respaldo")
	Texts.Put("backup_restore_info", "Restaura datos de un archivo .lockzero. Necesitarás la frase usada al crear el respaldo.")
	Texts.Put("backup_paste", "Pegar Respaldo")
	Texts.Put("backup_paste_instructions", "Abre el archivo .lockzero en un editor de texto, copia todo el contenido y pégalo aquí.")
	Texts.Put("backup_paste_hint", "Pega aquí el contenido del respaldo...")
	Texts.Put("backup_paste_empty", "Pega el contenido del respaldo")
	Texts.Put("backup_invalid", "Formato de respaldo inválido")
	Texts.Put("backup_verify", "VERIFICAR")
	Texts.Put("backup_test", "Probar Respaldo")
	Texts.Put("backup_test_info", "Verifica si el respaldo puede abrirse. No cambia tus datos actuales.")
	Texts.Put("backup_tip", "CONSEJO: Usa una oración, fragmento de canción o frase que ya conozcas de memoria. ¡Así no necesitas anotarla!")
	Texts.Put("backup_phrase_hint", "Frase para proteger el respaldo")
	Texts.Put("backup_phrase_min", "La frase debe tener mínimo 6 caracteres")
	Texts.Put("backup_success", "¡Respaldo creado exitosamente!")
	Texts.Put("backup_saved_at", "Guardado en:")
	Texts.Put("backup_error", "Error al crear respaldo")
	Texts.Put("backup_none_found", "No se encontró archivo .lockzero")
	Texts.Put("backup_phrase_backup", "Frase del respaldo")
	Texts.Put("backup_enter_phrase", "Ingresa la frase usada al crear el respaldo:")
	Texts.Put("backup_confirm_restore", "ATENCIÓN: Esto agregará los datos del respaldo a tus datos actuales.")
	Texts.Put("backup_continue", "¿Deseas continuar?")
	Texts.Put("backup_restored", "¡Respaldo restaurado!")
	Texts.Put("backup_groups", "Grupos:")
	Texts.Put("backup_entries", "Contraseñas:")
	Texts.Put("backup_notes", "Notas:")
	Texts.Put("backup_valid", "¡Respaldo VÁLIDO!")
	Texts.Put("backup_created_at", "Creado el:")
	Texts.Put("backup_test_ok", "Prueba OK")
	Texts.Put("backup_test_failed", "Frase incorrecta o archivo corrupto")
	Texts.Put("backup_wrong_phrase", "Frase incorrecta o archivo corrupto")
	Texts.Put("backup_share_question", "¿Compartir el archivo de respaldo?")
	Texts.Put("share_error", "Error al compartir")

	'=== IMPORT CSV ===
	Texts.Put("import_csv", "Importar CSV")
	Texts.Put("csv_entries_found", "entradas encontradas")
	Texts.Put("csv_selected", "Seleccionadas")
	Texts.Put("csv_select_all", "Seleccionar Todos")
	Texts.Put("csv_deselect_all", "Deseleccionar Todos")
	Texts.Put("csv_select_group", "Seleccionar Grupo")
	Texts.Put("csv_new_group", "Nuevo Grupo")
	Texts.Put("csv_import_btn", "Importar")
	Texts.Put("csv_imported", "entradas importadas")
	Texts.Put("csv_updated", "actualizadas")
	Texts.Put("csv_skipped", "omitidas (incompletas)")
	Texts.Put("csv_no_entries", "Sin entradas válidas en CSV")
	Texts.Put("csv_no_groups", "Sin grupos existentes")
	Texts.Put("csv_select_at_least_one", "Selecciona al menos una entrada")
	Texts.Put("csv_select_group_first", "Selecciona o crea un grupo primero")
	Texts.Put("csv_error_parse", "Error al leer archivo CSV")

	'CSV Import Instructions
	Texts.Put("csv_how_to_title", "Cómo Importar de Chrome")
	Texts.Put("csv_how_to_1", "1. En PC: Chrome → Menú (⋮) → Contraseñas")
	Texts.Put("csv_how_to_2", "2. Administrador de contraseñas → Configuración (⚙)")
	Texts.Put("csv_how_to_3", "3. Exportar contraseñas → Descargar archivo")
	Texts.Put("csv_how_to_4", "4. Envía el CSV al celular (WhatsApp, etc)")
	Texts.Put("csv_how_to_5", "5. Toca el archivo → Abrir con → LockZero")
	Texts.Put("understood", "Entendido")
End Sub

Private Sub LoadHebrew
	'=== APP ===
	Texts.Put("app_name", "LockZero")
	Texts.Put("app_tagline", "Lock and ZERO worries")
	Texts.Put("app_slogan", "שמור את המידע שלך עם אפס דאגות")
	Texts.Put("free_version", "גרסה חינמית")

	'=== GENERAL ===
	Texts.Put("ok", "אישור")
	Texts.Put("cancel", "ביטול")
	Texts.Put("save", "שמור")
	Texts.Put("delete", "מחק")
	Texts.Put("edit", "ערוך")
	Texts.Put("add", "הוסף")
	Texts.Put("close", "סגור")
	Texts.Put("back", "חזור")
	Texts.Put("next", "הבא")
	Texts.Put("continue", "המשך")
	Texts.Put("done", "סיום")
	Texts.Put("search", "חיפוש")
	Texts.Put("search_hint", "חפש לפי שם או URL...")
	Texts.Put("search_no_results", "לא נמצאו תוצאות")
	Texts.Put("copy", "העתק")
	Texts.Put("copied", "!הועתק")
	Texts.Put("show", "הצג")
	Texts.Put("hide", "הסתר")
	Texts.Put("view", "צפה")
	Texts.Put("yes", "כן")
	Texts.Put("no", "לא")
	Texts.Put("loading", "...טוען")
	Texts.Put("empty", "אין פריטים")
	Texts.Put("error", "שגיאה")
	Texts.Put("success", "הצלחה")
	Texts.Put("warning", "אזהרה")
	Texts.Put("discard", "בטל")
	Texts.Put("discard_changes", "לבטל שינויים?")
	Texts.Put("invalid_card_number", "מספר כרטיס לא תקין")

	'=== AUTHENTICATION ===
	Texts.Put("enter_passphrase", "הזן את המשפט הסודי שלך")
	Texts.Put("passphrase_hint", "המשפט האישי שלך...")
	Texts.Put("passphrase_confirm_new", "אשר שוב את המשפט החדש")
	Texts.Put("passphrase_mismatch", "המשפטים לא תואמים")
	Texts.Put("passphrase_min_8", "המשפט חייב להכיל לפחות 8 תווים")
	Texts.Put("passphrase_too_short", "משפט קצר מדי")
	Texts.Put("confirm", "אשר")
	Texts.Put("unlock", "פתח נעילה")
	Texts.Put("use_biometric", "השתמש בביומטרי")
	Texts.Put("wrong_passphrase", "משפט שגוי")
	Texts.Put("session_expired", "פג תוקף הפגישה")
	Texts.Put("session_remaining", "הפגישה תסתיים בעוד")
	Texts.Put("wait_timeout", "המתן")
	Texts.Put("attempts", "ניסיונות")
	Texts.Put("failed_attempts", "ניסיונות כושלים")
	Texts.Put("lock", "נעל")
	Texts.Put("lock_confirm_msg", "לנעול את הפגישה עכשיו?")
	Texts.Put("locked", "הפגישה נעולה")
	Texts.Put("session_active", "פגישה פעילה")

	'=== PASSPHRASE MODE ===
	Texts.Put("passphrase_mode", "מצב משפט סיסמה")
	Texts.Put("single_passphrase", "משפט יחיד")
	Texts.Put("single_passphrase_desc", "השתמש באותו משפט לכל הקטגוריות")
	Texts.Put("multi_passphrase", "משפט לכל קטגוריה")
	Texts.Put("multi_passphrase_desc", "לכל קטגוריה יכול להיות משפט משלה")
	Texts.Put("single_passphrase_warning", "מצב משפט יחיד פעיל. כדי להשתמש במשפטים שונים לכל קבוצה, שנה בהגדרות.")

	'=== CATEGORIES ===
	Texts.Put("passwords", "סיסמאות")
	Texts.Put("cards", "כרטיסים")
	Texts.Put("documents", "מסמכים")
	Texts.Put("notes", "הערות")
	Texts.Put("wifi", "Wi-Fi")

	'=== GROUPS ===
	Texts.Put("new_group", "קבוצה חדשה")
	Texts.Put("edit_group", "ערוך קבוצה")
	Texts.Put("group_name_hint", "שם הקבוצה")

	'=== PASSWORDS ===
	Texts.Put("password", "סיסמה")
	Texts.Put("username", "שם משתמש")
	Texts.Put("url", "URL/אתר")
	Texts.Put("site_name", "שם האתר")
	Texts.Put("site_name_hint", "לדוגמה: Google, Facebook...")
	Texts.Put("username_hint", "אימייל או שם משתמש")
	Texts.Put("password_hint", "סיסמה")
	Texts.Put("notes_hint", "הערות (אופציונלי)")
	Texts.Put("favorite", "מועדף")
	Texts.Put("new_password", "סיסמה חדשה")
	Texts.Put("add_password", "הוסף סיסמה")
	Texts.Put("edit_password", "ערוך סיסמה")
	Texts.Put("password_copied", "!הסיסמה הועתקה")
	Texts.Put("clipboard_clear", "הלוח נוקה")
	Texts.Put("seconds", "שניות")
	Texts.Put("generate_password", "צור סיסמה")
	Texts.Put("password_strength", "חוזק הסיסמה")
	Texts.Put("weak", "חלשה")
	Texts.Put("medium", "בינונית")
	Texts.Put("strong", "חזקה")
	Texts.Put("very_strong", "חזקה מאוד")

	'=== CARDS ===
	Texts.Put("card", "כרטיס")
	Texts.Put("card_number", "מספר כרטיס")
	Texts.Put("card_holder", "שם בעל הכרטיס")
	Texts.Put("expiry_date", "תוקף")
	Texts.Put("cvv", "CVV")
	Texts.Put("card_nickname", "כינוי לכרטיס")
	Texts.Put("add_card", "הוסף כרטיס")
	Texts.Put("edit_card", "ערוך כרטיס")

	'=== DOCUMENTS ===
	Texts.Put("document", "מסמך")
	Texts.Put("document_type", "סוג מסמך")
	Texts.Put("add_document", "הוסף מסמך")
	Texts.Put("take_photo", "צלם תמונה")
	Texts.Put("choose_photo", "בחר מהגלריה")
	Texts.Put("doc_cpf", "CPF")
	Texts.Put("doc_rg", "תעודת זהות")
	Texts.Put("doc_cnh", "רישיון נהיגה")
	Texts.Put("doc_passport", "דרכון")
	Texts.Put("doc_other", "אחר")

	'=== CARDS (system group) ===
	Texts.Put("card_name", "שם")
	Texts.Put("card_brand", "חברה")
	Texts.Put("card_expiry", "תוקף")
	Texts.Put("card_cvv", "CVV")
	Texts.Put("card_password", "סיסמה")
	Texts.Put("card_limit", "מסגרת")
	Texts.Put("clear_cards", "נקה כרטיסים")
	Texts.Put("clear_cards_confirm", "למחוק את כל הכרטיסים מקבוצה זו?")
	Texts.Put("new_card", "כרטיס חדש")

	'=== NOTES ===
	Texts.Put("note", "הערה")
	Texts.Put("note_title", "כותרת")
	Texts.Put("note_content", "תוכן")
	Texts.Put("new_note", "הערה חדשה")
	Texts.Put("add_note", "הוסף הערה")
	Texts.Put("edit_note", "ערוך הערה")

	'=== ATTACHMENTS ===
	Texts.Put("attachments", "קבצים מצורפים")
	Texts.Put("add_attachment", "צרף קובץ")
	Texts.Put("open_file", "פתח קובץ")
	Texts.Put("delete_attachment", "הסר קובץ")
	Texts.Put("no_attachments", "אין קבצים מצורפים")
	Texts.Put("file_not_found", "הקובץ לא נמצא")
	Texts.Put("select_file", "בחר קובץ")
	Texts.Put("attachment_added", "קובץ נוסף")
	Texts.Put("attachment_name", "שם הקובץ")
	Texts.Put("file_exists", "הקובץ כבר קיים")

	'=== NOTE GROUPS ===
	Texts.Put("note_groups", "קבוצות הערות")
	Texts.Put("note_group_new", "קבוצה חדשה")
	Texts.Put("note_group_name", "שם הקבוצה")
	Texts.Put("note_group_icon", "אימוג'י לקבוצה")
	Texts.Put("note_group_icon_hint", "לחץ לבחירת אימוג'י")
	Texts.Put("note_group_secure", "קבוצה מאובטחת (עם מנעול)")
	Texts.Put("note_group_open", "גישה חופשית")
	Texts.Put("note_group_delete", "מחק קבוצה")
	Texts.Put("note_group_delete_confirm", "למחוק קבוצה זו וכל ההערות שלה?")
	Texts.Put("note_group_empty", "אין קבוצות הערות. לחץ + ליצירה.")
	Texts.Put("note_group_setup_phrase", "הגדר משפט סיסמה לקבוצה זו")
	Texts.Put("note_type_text", "טקסט")
	Texts.Put("note_type_list", "רשימת משימות")
	Texts.Put("note_type_choose", "איזה סוג הערה?")
	Texts.Put("note_add_item", "הוסף פריט")
	Texts.Put("note_items_count", "%1 מתוך %2 פריטים")
	Texts.Put("note_share", "שתף")
	Texts.Put("note_share_confirm", "לייצא כטקסט פתוח?")
	Texts.Put("note_share_auth", "אשר לייצוא")
	Texts.Put("note_reorder", "החזק וגרור לשינוי סדר")
	Texts.Put("new_list", "רשימה חדשה")
	Texts.Put("new_text", "טקסט חדש")
	Texts.Put("add_item", "הוסף פריט")
	Texts.Put("title", "כותרת")
	Texts.Put("title_hint", "הזן את הכותרת")
	Texts.Put("item_hint", "הזן את הפריט")
	Texts.Put("filter_items", "...סנן פריטים")
	Texts.Put("share", "שתף")
	Texts.Put("share_which", "לשתף אילו פריטים?")
	Texts.Put("share_all", "הכל")
	Texts.Put("share_checked", "רק מסומנים")
	Texts.Put("content", "תוכן")
	Texts.Put("content_hint", "...הזן את התוכן")
	Texts.Put("mark_favorite", "סמן כמועדף")
	Texts.Put("confirm_delete_item", "למחוק פריט זה?")
	Texts.Put("edit_item", "ערוך פריט")
	Texts.Put("error_not_found", "לא נמצא")
	Texts.Put("of", "מתוך")
	Texts.Put("items", "פריטים")

	'=== WIFI ===
	Texts.Put("wifi_name", "שם הרשת (SSID)")
	Texts.Put("wifi_password", "סיסמת הרשת")
	Texts.Put("wifi_security", "סוג אבטחה")
	Texts.Put("add_wifi", "הוסף רשת")

	'=== GENERATOR ===
	Texts.Put("generator", "מחולל")
	Texts.Put("length", "אורך")
	Texts.Put("uppercase", "אותיות גדולות (A-Z)")
	Texts.Put("lowercase", "אותיות קטנות (a-z)")
	Texts.Put("numbers", "מספרים (0-9)")
	Texts.Put("symbols", "סימנים (!@#$)")
	Texts.Put("generate", "צור")
	Texts.Put("use_password", "השתמש בסיסמה זו")

	'=== SETTINGS ===
	Texts.Put("settings", "הגדרות")
	Texts.Put("settings_general", "כללי")
	Texts.Put("settings_security", "אבטחה")
	Texts.Put("data", "נתונים")
	Texts.Put("language", "שפה")
	Texts.Put("theme", "ערכת נושא")
	Texts.Put("theme_light", "בהיר")
	Texts.Put("theme_dark", "כהה")
	Texts.Put("session_timeout", "זמן פגישה")
	Texts.Put("clipboard_timeout", "נקה לוח")
	Texts.Put("biometric", "ביומטרי")
	Texts.Put("use_pin", "השתמש ב-PIN")
	Texts.Put("use_pin_desc", "PIN של 4-8 ספרות לפתיחת האפליקציה")
	Texts.Put("use_biometric_desc", "השתמש בטביעת אצבע או זיהוי פנים")
	Texts.Put("create_pin_msg", "תתבקש ליצור PIN של 4-8 ספרות.")
	Texts.Put("remove_pin_msg", "האם ברצונך להסיר את ה-PIN?")
	Texts.Put("biometric_enabled", "ביומטרי מופעל")
	Texts.Put("biometric_disabled", "ביומטרי מושבת")
	Texts.Put("pin_access", "גישה ב-PIN")
	Texts.Put("change_pin", "שנה PIN")
	Texts.Put("remove_pin", "הסר PIN")

	'=== PIN/BIOMETRIC - DIALOGS ===
	Texts.Put("pin_title", "הזן PIN")
	Texts.Put("pin_enter", "הזן את ה-PIN שלך")
	Texts.Put("pin_create", "צור PIN של 4-8 ספרות")
	Texts.Put("pin_confirm", "אשר PIN")
	Texts.Put("pin_wrong", "PIN שגוי")
	Texts.Put("pin_saved", "PIN נשמר בהצלחה")
	Texts.Put("pin_removed", "PIN הוסר")
	Texts.Put("pin_mismatch", "ה-PINs לא תואמים")
	Texts.Put("pin_too_short", "PIN חייב להיות 4-8 ספרות")
	Texts.Put("pin_digits", "4-8 ספרות")
	Texts.Put("pin_current", "הזן PIN נוכחי")
	Texts.Put("biometric_title", "אימות")
	Texts.Put("biometric_prompt", "השתמש בטביעת האצבע להמשך")
	Texts.Put("biometric_or_pin", "או הזן PIN")
	Texts.Put("biometric_failed", "האימות נכשל")
	Texts.Put("biometric_unavailable", "ביומטרי לא זמין")
	Texts.Put("about", "אודות")
	Texts.Put("version", "גרסה")
	Texts.Put("clear_data", "מחק את כל הנתונים")
	Texts.Put("clear_data_desc", "מסיר את כל הסיסמאות, הקבוצות וההערות")
	Texts.Put("clear_data_confirm", "אזהרה: פעולה זו תמחק לצמיתות את כל הנתונים שלך (סיסמאות, קבוצות, הערות). לא ניתן לבטל פעולה זו. להמשיך?")
	Texts.Put("data_cleared", "כל הנתונים נמחקו")
	Texts.Put("export_data", "ייצא נתונים")
	Texts.Put("import_data", "ייבא נתונים")
	Texts.Put("backup", "גיבוי")
	Texts.Put("minute", "דקה")
	Texts.Put("minutes", "דקות")

	'=== CONFIRMATIONS ===
	Texts.Put("confirm_delete", "אשר מחיקה")
	Texts.Put("confirm_delete_msg", "האם באמת ברצונך למחוק פריט זה?")
	Texts.Put("confirm_exit", "האם ברצונך לצאת?")

	'=== ONBOARDING ===
	Texts.Put("onb_welcome_title", "ברוכים הבאים ל-LockZero")
	Texts.Put("onb_welcome_text", "Lock and ZERO worries" & Chr(10) & Chr(10) & "LockZero הוא הכספת הדיגיטלית האישית שלך." & Chr(10) & Chr(10) & "• אפס אינטרנט - הנתונים שלך לא יוצאים מהמכשיר" & Chr(10) & "• אפס ידע - גם אנחנו לא יודעים את המשפט שלך" & Chr(10) & "• אפס שחזור - אתה האחראי היחיד" & Chr(10) & "• ללא דמי מנוי - חינם לנצח")
	Texts.Put("onb_warning_title", "⚠️ אזהרה חשובה")
	Texts.Put("onb_warning_text", "קרא בעיון:" & Chr(10) & Chr(10) & "1. משפט הסיסמה שלך לא נשמר בשום מקום." & Chr(10) & Chr(10) & "2. אם תשכח את משפט הסיסמה, תאבד את כל הנתונים שלך." & Chr(10) & Chr(10) & "3. אין 'שכחתי סיסמה'. אין שחזור." & Chr(10) & Chr(10) & "4. אף אחד לא יכול לעזור לך. לא אנחנו, לא גוגל, אף אחד." & Chr(10) & Chr(10) & "5. גיבויים מגנים מפני אובדן המכשיר, לא משכחת המשפט." & Chr(10) & Chr(10) & "💡 טיפ: השתמש בתפילה, בשיר או במשפט אישי שלעולם לא תשכח.")
	Texts.Put("onb_understand", "אני מבין שאין שחזור ואני האחראי היחיד")
	Texts.Put("onb_accept", "אשר והמשך")
	Texts.Put("onb_setup_title", "צור את משפט הסיסמה שלך")
	Texts.Put("onb_setup_info", "משפט זה ישמש להצפנת כל הנתונים שלך. בחר משהו שתוכל לזכור, אבל שקשה לנחש." & Chr(10) & Chr(10) & "מינימום: 8 תווים")
	Texts.Put("onb_passphrase_hint", "הזן את משפט הסיסמה שלך")
	Texts.Put("onb_passphrase_confirm", "אשר את משפט הסיסמה שלך")
	Texts.Put("onb_create_continue", "צור והמשך")
	Texts.Put("onb_backup_title", "גיבוי אופציונלי")
	Texts.Put("onb_backup_text", "אתה יכול ליצור גיבוי עכשיו או מאוחר יותר בהגדרות." & Chr(10) & Chr(10) & "גיבוי זה יהיה מוגן על ידי משפט הסיסמה שלך." & Chr(10) & Chr(10) & "שמור את קובץ ה-.lockzero במקום בטוח (USB, מחשב, ענן אישי).")
	Texts.Put("onb_create_backup", "צור גיבוי עכשיו")
	Texts.Put("onb_skip_backup", "דלג לעת עתה")
	Texts.Put("onb_complete_title", "!הכל מוכן")
	Texts.Put("onb_complete_text", "ה-LockZero שלך מוגדר ומוגן." & Chr(10) & Chr(10) & "זכור:" & Chr(10) & "• משפט הסיסמה שלך: לעולם אל תשכח" & Chr(10) & "• גיבויים: עשה באופן קבוע" & Chr(10) & "• אבטחה: 100% בידיים שלך" & Chr(10) & Chr(10) & "Lock and ZERO worries!")
	Texts.Put("onb_start", "התחל להשתמש")
	Texts.Put("onb_min_chars", "המשפט חייב להכיל לפחות 8 תווים")
	Texts.Put("onb_not_match", "המשפטים לא תואמים")
	Texts.Put("onb_must_accept", "עליך לאשר את התנאים")
	Texts.Put("onb_complete_setup", "השלם את ההגדרה הראשונית")

	'=== ERRORS ===
	Texts.Put("error_empty_field", "מלא את כל השדות")
	Texts.Put("error_invalid_data", "נתונים לא תקינים")
	Texts.Put("error_save", "שגיאה בשמירה")
	Texts.Put("error_load", "שגיאה בטעינה")

	'=== BACKUP ===
	Texts.Put("backup_last", "גיבוי אחרון:")
	Texts.Put("backup_never", "לא בוצע גיבוי")
	Texts.Put("backup_export", "ייצוא")
	Texts.Put("backup_create", "צור גיבוי עכשיו")
	Texts.Put("backup_create_info", "יוצר קובץ .lockzero מוצפן עם כל הנתונים שלך.")
	Texts.Put("backup_import", "ייבוא")
	Texts.Put("backup_restore", "שחזר גיבוי")
	Texts.Put("backup_restore_info", "משחזר נתונים מקובץ .lockzero. תצטרך את המשפט שהשתמשת בעת יצירת הגיבוי.")
	Texts.Put("backup_paste", "הדבק גיבוי")
	Texts.Put("backup_paste_instructions", "פתח את קובץ ה-.lockzero בעורך טקסט, העתק את כל התוכן והדבק כאן.")
	Texts.Put("backup_paste_hint", "הדבק כאן את תוכן הגיבוי...")
	Texts.Put("backup_paste_empty", "הדבק את תוכן הגיבוי")
	Texts.Put("backup_invalid", "פורמט גיבוי לא תקין")
	Texts.Put("backup_verify", "אמת")
	Texts.Put("backup_test", "בדוק גיבוי")
	Texts.Put("backup_test_info", "בודק אם ניתן לפתוח את הגיבוי. לא משנה את הנתונים הנוכחיים שלך.")
	Texts.Put("backup_tip", "טיפ: השתמש בתפילה, בשיר או במשפט שאתה כבר יודע בעל פה. אין צורך לרשום!")
	Texts.Put("backup_phrase_hint", "משפט להגנה על הגיבוי")
	Texts.Put("backup_phrase_min", "המשפט חייב להכיל לפחות 6 תווים")
	Texts.Put("backup_success", "!הגיבוי נוצר בהצלחה")
	Texts.Put("backup_saved_at", "נשמר ב:")
	Texts.Put("backup_error", "שגיאה ביצירת גיבוי")
	Texts.Put("backup_none_found", "לא נמצא קובץ .lockzero")
	Texts.Put("backup_phrase_backup", "משפט הגיבוי")
	Texts.Put("backup_enter_phrase", "הזן את המשפט שהשתמשת בעת יצירת הגיבוי:")
	Texts.Put("backup_confirm_restore", "אזהרה: פעולה זו תוסיף את נתוני הגיבוי לנתונים הנוכחיים שלך.")
	Texts.Put("backup_continue", "להמשיך?")
	Texts.Put("backup_restored", "!הגיבוי שוחזר")
	Texts.Put("backup_groups", "קבוצות:")
	Texts.Put("backup_entries", "סיסמאות:")
	Texts.Put("backup_notes", "הערות:")
	Texts.Put("backup_valid", "!גיבוי תקין")
	Texts.Put("backup_created_at", "נוצר ב:")
	Texts.Put("backup_test_ok", "הבדיקה עברה")
	Texts.Put("backup_test_failed", "משפט שגוי או קובץ פגום")
	Texts.Put("backup_wrong_phrase", "משפט שגוי או קובץ פגום")
	Texts.Put("backup_share_question", "לשתף את קובץ הגיבוי?")
	Texts.Put("share_error", "שגיאה בשיתוף")

	'=== IMPORT CSV ===
	Texts.Put("import_csv", "ייבא CSV")
	Texts.Put("csv_entries_found", "רשומות נמצאו")
	Texts.Put("csv_selected", "נבחרו")
	Texts.Put("csv_select_all", "בחר הכל")
	Texts.Put("csv_deselect_all", "בטל בחירה")
	Texts.Put("csv_select_group", "בחר קבוצה")
	Texts.Put("csv_new_group", "קבוצה חדשה")
	Texts.Put("csv_import_btn", "ייבא")
	Texts.Put("csv_imported", "רשומות יובאו")
	Texts.Put("csv_updated", "עודכנו")
	Texts.Put("csv_skipped", "דולגו (לא מלאות)")
	Texts.Put("csv_no_entries", "אין רשומות תקינות ב-CSV")
	Texts.Put("csv_no_groups", "אין קבוצות קיימות")
	Texts.Put("csv_select_at_least_one", "בחר לפחות רשומה אחת")
	Texts.Put("csv_select_group_first", "בחר או צור קבוצה קודם")
	Texts.Put("csv_error_parse", "שגיאה בקריאת קובץ CSV")

	'CSV Import Instructions
	Texts.Put("csv_how_to_title", "איך לייבא מ-Chrome")
	Texts.Put("csv_how_to_1", "1. במחשב: Chrome → תפריט (⋮) → סיסמאות")
	Texts.Put("csv_how_to_2", "2. מנהל הסיסמאות → הגדרות (⚙)")
	Texts.Put("csv_how_to_3", "3. ייצא סיסמאות → הורד קובץ")
	Texts.Put("csv_how_to_4", "4. שלח את ה-CSV לטלפון (WhatsApp וכו')")
	Texts.Put("csv_how_to_5", "5. לחץ על הקובץ → פתח עם → LockZero")
	Texts.Put("understood", "הבנתי")
End Sub
