package com.lockzero;


import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.BALayout;
import anywheresoftware.b4a.debug.*;

public class modlang {
private static modlang mostCurrent = new modlang();
public static Object getObject() {
    throw new RuntimeException("Code module does not support this method.");
}
 public anywheresoftware.b4a.keywords.Common __c = null;
public static String _currentlang = "";
public static anywheresoftware.b4a.objects.collections.Map _texts = null;
public b4a.example.dateutils _dateutils = null;
public com.lockzero.main _main = null;
public com.lockzero.starter _starter = null;
public com.lockzero.modbackup _modbackup = null;
public com.lockzero.modnotes _modnotes = null;
public com.lockzero.modpasswords _modpasswords = null;
public com.lockzero.modsecurity _modsecurity = null;
public com.lockzero.modsession _modsession = null;
public com.lockzero.modtheme _modtheme = null;
public com.lockzero.b4xpages _b4xpages = null;
public com.lockzero.b4xcollections _b4xcollections = null;
public com.lockzero.xuiviewsutils _xuiviewsutils = null;
public static String  _getcurrentlanguage(anywheresoftware.b4a.BA _ba) throws Exception{
 //BA.debugLineNum = 22;BA.debugLine="Public Sub GetCurrentLanguage As String";
 //BA.debugLineNum = 23;BA.debugLine="Return CurrentLang";
if (true) return _currentlang;
 //BA.debugLineNum = 24;BA.debugLine="End Sub";
return "";
}
public static String  _getlanguagename(anywheresoftware.b4a.BA _ba) throws Exception{
 //BA.debugLineNum = 26;BA.debugLine="Public Sub GetLanguageName As String";
 //BA.debugLineNum = 27;BA.debugLine="Select CurrentLang";
switch (BA.switchObjectToInt(_currentlang,"pt","en")) {
case 0: {
 //BA.debugLineNum = 28;BA.debugLine="Case \"pt\": Return \"Portugues\"";
if (true) return "Portugues";
 break; }
case 1: {
 //BA.debugLineNum = 29;BA.debugLine="Case \"en\": Return \"English\"";
if (true) return "English";
 break; }
default: {
 //BA.debugLineNum = 30;BA.debugLine="Case Else: Return \"Portugues\"";
if (true) return "Portugues";
 break; }
}
;
 //BA.debugLineNum = 32;BA.debugLine="End Sub";
return "";
}
public static String  _gettext(anywheresoftware.b4a.BA _ba,String _key) throws Exception{
 //BA.debugLineNum = 44;BA.debugLine="Public Sub GetText(key As String) As String";
 //BA.debugLineNum = 45;BA.debugLine="Return T(key)";
if (true) return _t(_ba,_key);
 //BA.debugLineNum = 46;BA.debugLine="End Sub";
return "";
}
public static String  _init(anywheresoftware.b4a.BA _ba) throws Exception{
 //BA.debugLineNum = 10;BA.debugLine="Public Sub Init";
 //BA.debugLineNum = 11;BA.debugLine="CurrentLang = ModSecurity.GetLanguage";
_currentlang = mostCurrent._modsecurity._getlanguage /*String*/ (_ba);
 //BA.debugLineNum = 12;BA.debugLine="If CurrentLang = \"\" Then CurrentLang = \"pt\"";
if ((_currentlang).equals("")) { 
_currentlang = "pt";};
 //BA.debugLineNum = 13;BA.debugLine="LoadTexts";
_loadtexts(_ba);
 //BA.debugLineNum = 14;BA.debugLine="End Sub";
return "";
}
public static String  _loadenglish(anywheresoftware.b4a.BA _ba) throws Exception{
 //BA.debugLineNum = 307;BA.debugLine="Private Sub LoadEnglish";
 //BA.debugLineNum = 309;BA.debugLine="Texts.Put(\"app_name\", \"LockZero\")";
_texts.Put((Object)("app_name"),(Object)("LockZero"));
 //BA.debugLineNum = 310;BA.debugLine="Texts.Put(\"app_tagline\", \"Lock and ZERO worries\")";
_texts.Put((Object)("app_tagline"),(Object)("Lock and ZERO worries"));
 //BA.debugLineNum = 311;BA.debugLine="Texts.Put(\"app_slogan\", \"Store your information w";
_texts.Put((Object)("app_slogan"),(Object)("Store your information with ZERO worries"));
 //BA.debugLineNum = 312;BA.debugLine="Texts.Put(\"free_version\", \"Free Version\")";
_texts.Put((Object)("free_version"),(Object)("Free Version"));
 //BA.debugLineNum = 315;BA.debugLine="Texts.Put(\"ok\", \"OK\")";
_texts.Put((Object)("ok"),(Object)("OK"));
 //BA.debugLineNum = 316;BA.debugLine="Texts.Put(\"cancel\", \"Cancel\")";
_texts.Put((Object)("cancel"),(Object)("Cancel"));
 //BA.debugLineNum = 317;BA.debugLine="Texts.Put(\"save\", \"Save\")";
_texts.Put((Object)("save"),(Object)("Save"));
 //BA.debugLineNum = 318;BA.debugLine="Texts.Put(\"delete\", \"Delete\")";
_texts.Put((Object)("delete"),(Object)("Delete"));
 //BA.debugLineNum = 319;BA.debugLine="Texts.Put(\"edit\", \"Edit\")";
_texts.Put((Object)("edit"),(Object)("Edit"));
 //BA.debugLineNum = 320;BA.debugLine="Texts.Put(\"add\", \"Add\")";
_texts.Put((Object)("add"),(Object)("Add"));
 //BA.debugLineNum = 321;BA.debugLine="Texts.Put(\"close\", \"Close\")";
_texts.Put((Object)("close"),(Object)("Close"));
 //BA.debugLineNum = 322;BA.debugLine="Texts.Put(\"back\", \"Back\")";
_texts.Put((Object)("back"),(Object)("Back"));
 //BA.debugLineNum = 323;BA.debugLine="Texts.Put(\"next\", \"Next\")";
_texts.Put((Object)("next"),(Object)("Next"));
 //BA.debugLineNum = 324;BA.debugLine="Texts.Put(\"done\", \"Done\")";
_texts.Put((Object)("done"),(Object)("Done"));
 //BA.debugLineNum = 325;BA.debugLine="Texts.Put(\"search\", \"Search\")";
_texts.Put((Object)("search"),(Object)("Search"));
 //BA.debugLineNum = 326;BA.debugLine="Texts.Put(\"copy\", \"Copy\")";
_texts.Put((Object)("copy"),(Object)("Copy"));
 //BA.debugLineNum = 327;BA.debugLine="Texts.Put(\"copied\", \"Copied!\")";
_texts.Put((Object)("copied"),(Object)("Copied!"));
 //BA.debugLineNum = 328;BA.debugLine="Texts.Put(\"show\", \"Show\")";
_texts.Put((Object)("show"),(Object)("Show"));
 //BA.debugLineNum = 329;BA.debugLine="Texts.Put(\"hide\", \"Hide\")";
_texts.Put((Object)("hide"),(Object)("Hide"));
 //BA.debugLineNum = 330;BA.debugLine="Texts.Put(\"view\", \"View\")";
_texts.Put((Object)("view"),(Object)("View"));
 //BA.debugLineNum = 331;BA.debugLine="Texts.Put(\"yes\", \"Yes\")";
_texts.Put((Object)("yes"),(Object)("Yes"));
 //BA.debugLineNum = 332;BA.debugLine="Texts.Put(\"no\", \"No\")";
_texts.Put((Object)("no"),(Object)("No"));
 //BA.debugLineNum = 333;BA.debugLine="Texts.Put(\"loading\", \"Loading...\")";
_texts.Put((Object)("loading"),(Object)("Loading..."));
 //BA.debugLineNum = 334;BA.debugLine="Texts.Put(\"empty\", \"No items\")";
_texts.Put((Object)("empty"),(Object)("No items"));
 //BA.debugLineNum = 335;BA.debugLine="Texts.Put(\"error\", \"Error\")";
_texts.Put((Object)("error"),(Object)("Error"));
 //BA.debugLineNum = 336;BA.debugLine="Texts.Put(\"success\", \"Success\")";
_texts.Put((Object)("success"),(Object)("Success"));
 //BA.debugLineNum = 337;BA.debugLine="Texts.Put(\"warning\", \"Warning\")";
_texts.Put((Object)("warning"),(Object)("Warning"));
 //BA.debugLineNum = 340;BA.debugLine="Texts.Put(\"enter_passphrase\", \"Enter your secret";
_texts.Put((Object)("enter_passphrase"),(Object)("Enter your secret phrase"));
 //BA.debugLineNum = 341;BA.debugLine="Texts.Put(\"passphrase_hint\", \"Your personal phras";
_texts.Put((Object)("passphrase_hint"),(Object)("Your personal phrase..."));
 //BA.debugLineNum = 342;BA.debugLine="Texts.Put(\"passphrase_min_8\", \"Phrase must have a";
_texts.Put((Object)("passphrase_min_8"),(Object)("Phrase must have at least 8 characters"));
 //BA.debugLineNum = 343;BA.debugLine="Texts.Put(\"passphrase_too_short\", \"Phrase too sho";
_texts.Put((Object)("passphrase_too_short"),(Object)("Phrase too short"));
 //BA.debugLineNum = 344;BA.debugLine="Texts.Put(\"confirm\", \"Confirm\")";
_texts.Put((Object)("confirm"),(Object)("Confirm"));
 //BA.debugLineNum = 345;BA.debugLine="Texts.Put(\"unlock\", \"Unlock\")";
_texts.Put((Object)("unlock"),(Object)("Unlock"));
 //BA.debugLineNum = 346;BA.debugLine="Texts.Put(\"use_biometric\", \"Use biometric\")";
_texts.Put((Object)("use_biometric"),(Object)("Use biometric"));
 //BA.debugLineNum = 347;BA.debugLine="Texts.Put(\"wrong_passphrase\", \"Wrong phrase\")";
_texts.Put((Object)("wrong_passphrase"),(Object)("Wrong phrase"));
 //BA.debugLineNum = 348;BA.debugLine="Texts.Put(\"session_expired\", \"Session expired\")";
_texts.Put((Object)("session_expired"),(Object)("Session expired"));
 //BA.debugLineNum = 349;BA.debugLine="Texts.Put(\"session_remaining\", \"Session expires i";
_texts.Put((Object)("session_remaining"),(Object)("Session expires in"));
 //BA.debugLineNum = 350;BA.debugLine="Texts.Put(\"wait_timeout\", \"Wait\")";
_texts.Put((Object)("wait_timeout"),(Object)("Wait"));
 //BA.debugLineNum = 351;BA.debugLine="Texts.Put(\"attempts\", \"attempts\")";
_texts.Put((Object)("attempts"),(Object)("attempts"));
 //BA.debugLineNum = 352;BA.debugLine="Texts.Put(\"failed_attempts\", \"failed attempts\")";
_texts.Put((Object)("failed_attempts"),(Object)("failed attempts"));
 //BA.debugLineNum = 353;BA.debugLine="Texts.Put(\"lock\", \"Lock\")";
_texts.Put((Object)("lock"),(Object)("Lock"));
 //BA.debugLineNum = 354;BA.debugLine="Texts.Put(\"lock_confirm_msg\", \"Lock the session n";
_texts.Put((Object)("lock_confirm_msg"),(Object)("Lock the session now?"));
 //BA.debugLineNum = 355;BA.debugLine="Texts.Put(\"locked\", \"Session locked\")";
_texts.Put((Object)("locked"),(Object)("Session locked"));
 //BA.debugLineNum = 358;BA.debugLine="Texts.Put(\"passphrase_mode\", \"Passphrase mode\")";
_texts.Put((Object)("passphrase_mode"),(Object)("Passphrase mode"));
 //BA.debugLineNum = 359;BA.debugLine="Texts.Put(\"single_passphrase\", \"Single passphrase";
_texts.Put((Object)("single_passphrase"),(Object)("Single passphrase"));
 //BA.debugLineNum = 360;BA.debugLine="Texts.Put(\"single_passphrase_desc\", \"Use the same";
_texts.Put((Object)("single_passphrase_desc"),(Object)("Use the same passphrase for all categories"));
 //BA.debugLineNum = 361;BA.debugLine="Texts.Put(\"multi_passphrase\", \"Per category passp";
_texts.Put((Object)("multi_passphrase"),(Object)("Per category passphrase"));
 //BA.debugLineNum = 362;BA.debugLine="Texts.Put(\"multi_passphrase_desc\", \"Each category";
_texts.Put((Object)("multi_passphrase_desc"),(Object)("Each category can have its own passphrase"));
 //BA.debugLineNum = 365;BA.debugLine="Texts.Put(\"passwords\", \"Passwords\")";
_texts.Put((Object)("passwords"),(Object)("Passwords"));
 //BA.debugLineNum = 366;BA.debugLine="Texts.Put(\"cards\", \"Cards\")";
_texts.Put((Object)("cards"),(Object)("Cards"));
 //BA.debugLineNum = 367;BA.debugLine="Texts.Put(\"documents\", \"Documents\")";
_texts.Put((Object)("documents"),(Object)("Documents"));
 //BA.debugLineNum = 368;BA.debugLine="Texts.Put(\"notes\", \"Notes\")";
_texts.Put((Object)("notes"),(Object)("Notes"));
 //BA.debugLineNum = 369;BA.debugLine="Texts.Put(\"wifi\", \"Wi-Fi\")";
_texts.Put((Object)("wifi"),(Object)("Wi-Fi"));
 //BA.debugLineNum = 372;BA.debugLine="Texts.Put(\"new_group\", \"New Group\")";
_texts.Put((Object)("new_group"),(Object)("New Group"));
 //BA.debugLineNum = 373;BA.debugLine="Texts.Put(\"edit_group\", \"Edit Group\")";
_texts.Put((Object)("edit_group"),(Object)("Edit Group"));
 //BA.debugLineNum = 374;BA.debugLine="Texts.Put(\"group_name_hint\", \"Group name\")";
_texts.Put((Object)("group_name_hint"),(Object)("Group name"));
 //BA.debugLineNum = 377;BA.debugLine="Texts.Put(\"password\", \"Password\")";
_texts.Put((Object)("password"),(Object)("Password"));
 //BA.debugLineNum = 378;BA.debugLine="Texts.Put(\"username\", \"Username\")";
_texts.Put((Object)("username"),(Object)("Username"));
 //BA.debugLineNum = 379;BA.debugLine="Texts.Put(\"url\", \"URL/Website\")";
_texts.Put((Object)("url"),(Object)("URL/Website"));
 //BA.debugLineNum = 380;BA.debugLine="Texts.Put(\"site_name\", \"Site name\")";
_texts.Put((Object)("site_name"),(Object)("Site name"));
 //BA.debugLineNum = 381;BA.debugLine="Texts.Put(\"site_name_hint\", \"Ex: Google, Facebook";
_texts.Put((Object)("site_name_hint"),(Object)("Ex: Google, Facebook..."));
 //BA.debugLineNum = 382;BA.debugLine="Texts.Put(\"username_hint\", \"Email or username\")";
_texts.Put((Object)("username_hint"),(Object)("Email or username"));
 //BA.debugLineNum = 383;BA.debugLine="Texts.Put(\"password_hint\", \"Password\")";
_texts.Put((Object)("password_hint"),(Object)("Password"));
 //BA.debugLineNum = 384;BA.debugLine="Texts.Put(\"notes_hint\", \"Notes (optional)\")";
_texts.Put((Object)("notes_hint"),(Object)("Notes (optional)"));
 //BA.debugLineNum = 385;BA.debugLine="Texts.Put(\"favorite\", \"Favorite\")";
_texts.Put((Object)("favorite"),(Object)("Favorite"));
 //BA.debugLineNum = 386;BA.debugLine="Texts.Put(\"new_password\", \"New Password\")";
_texts.Put((Object)("new_password"),(Object)("New Password"));
 //BA.debugLineNum = 387;BA.debugLine="Texts.Put(\"add_password\", \"Add password\")";
_texts.Put((Object)("add_password"),(Object)("Add password"));
 //BA.debugLineNum = 388;BA.debugLine="Texts.Put(\"edit_password\", \"Edit password\")";
_texts.Put((Object)("edit_password"),(Object)("Edit password"));
 //BA.debugLineNum = 389;BA.debugLine="Texts.Put(\"password_copied\", \"Password copied!\")";
_texts.Put((Object)("password_copied"),(Object)("Password copied!"));
 //BA.debugLineNum = 390;BA.debugLine="Texts.Put(\"clipboard_clear\", \"Clipboard clears in";
_texts.Put((Object)("clipboard_clear"),(Object)("Clipboard clears in"));
 //BA.debugLineNum = 391;BA.debugLine="Texts.Put(\"seconds\", \"seconds\")";
_texts.Put((Object)("seconds"),(Object)("seconds"));
 //BA.debugLineNum = 392;BA.debugLine="Texts.Put(\"generate_password\", \"Generate password";
_texts.Put((Object)("generate_password"),(Object)("Generate password"));
 //BA.debugLineNum = 393;BA.debugLine="Texts.Put(\"password_strength\", \"Password strength";
_texts.Put((Object)("password_strength"),(Object)("Password strength"));
 //BA.debugLineNum = 394;BA.debugLine="Texts.Put(\"weak\", \"Weak\")";
_texts.Put((Object)("weak"),(Object)("Weak"));
 //BA.debugLineNum = 395;BA.debugLine="Texts.Put(\"medium\", \"Medium\")";
_texts.Put((Object)("medium"),(Object)("Medium"));
 //BA.debugLineNum = 396;BA.debugLine="Texts.Put(\"strong\", \"Strong\")";
_texts.Put((Object)("strong"),(Object)("Strong"));
 //BA.debugLineNum = 397;BA.debugLine="Texts.Put(\"very_strong\", \"Very strong\")";
_texts.Put((Object)("very_strong"),(Object)("Very strong"));
 //BA.debugLineNum = 400;BA.debugLine="Texts.Put(\"card\", \"Card\")";
_texts.Put((Object)("card"),(Object)("Card"));
 //BA.debugLineNum = 401;BA.debugLine="Texts.Put(\"card_number\", \"Card number\")";
_texts.Put((Object)("card_number"),(Object)("Card number"));
 //BA.debugLineNum = 402;BA.debugLine="Texts.Put(\"card_holder\", \"Cardholder name\")";
_texts.Put((Object)("card_holder"),(Object)("Cardholder name"));
 //BA.debugLineNum = 403;BA.debugLine="Texts.Put(\"expiry_date\", \"Expiry date\")";
_texts.Put((Object)("expiry_date"),(Object)("Expiry date"));
 //BA.debugLineNum = 404;BA.debugLine="Texts.Put(\"cvv\", \"CVV\")";
_texts.Put((Object)("cvv"),(Object)("CVV"));
 //BA.debugLineNum = 405;BA.debugLine="Texts.Put(\"card_nickname\", \"Card nickname\")";
_texts.Put((Object)("card_nickname"),(Object)("Card nickname"));
 //BA.debugLineNum = 406;BA.debugLine="Texts.Put(\"add_card\", \"Add card\")";
_texts.Put((Object)("add_card"),(Object)("Add card"));
 //BA.debugLineNum = 407;BA.debugLine="Texts.Put(\"edit_card\", \"Edit card\")";
_texts.Put((Object)("edit_card"),(Object)("Edit card"));
 //BA.debugLineNum = 410;BA.debugLine="Texts.Put(\"document\", \"Document\")";
_texts.Put((Object)("document"),(Object)("Document"));
 //BA.debugLineNum = 411;BA.debugLine="Texts.Put(\"document_type\", \"Document type\")";
_texts.Put((Object)("document_type"),(Object)("Document type"));
 //BA.debugLineNum = 412;BA.debugLine="Texts.Put(\"add_document\", \"Add document\")";
_texts.Put((Object)("add_document"),(Object)("Add document"));
 //BA.debugLineNum = 413;BA.debugLine="Texts.Put(\"take_photo\", \"Take photo\")";
_texts.Put((Object)("take_photo"),(Object)("Take photo"));
 //BA.debugLineNum = 414;BA.debugLine="Texts.Put(\"choose_photo\", \"Choose from gallery\")";
_texts.Put((Object)("choose_photo"),(Object)("Choose from gallery"));
 //BA.debugLineNum = 415;BA.debugLine="Texts.Put(\"doc_cpf\", \"CPF\")";
_texts.Put((Object)("doc_cpf"),(Object)("CPF"));
 //BA.debugLineNum = 416;BA.debugLine="Texts.Put(\"doc_rg\", \"RG\")";
_texts.Put((Object)("doc_rg"),(Object)("RG"));
 //BA.debugLineNum = 417;BA.debugLine="Texts.Put(\"doc_cnh\", \"Driver License\")";
_texts.Put((Object)("doc_cnh"),(Object)("Driver License"));
 //BA.debugLineNum = 418;BA.debugLine="Texts.Put(\"doc_passport\", \"Passport\")";
_texts.Put((Object)("doc_passport"),(Object)("Passport"));
 //BA.debugLineNum = 419;BA.debugLine="Texts.Put(\"doc_other\", \"Other\")";
_texts.Put((Object)("doc_other"),(Object)("Other"));
 //BA.debugLineNum = 422;BA.debugLine="Texts.Put(\"note\", \"Note\")";
_texts.Put((Object)("note"),(Object)("Note"));
 //BA.debugLineNum = 423;BA.debugLine="Texts.Put(\"note_title\", \"Title\")";
_texts.Put((Object)("note_title"),(Object)("Title"));
 //BA.debugLineNum = 424;BA.debugLine="Texts.Put(\"note_content\", \"Content\")";
_texts.Put((Object)("note_content"),(Object)("Content"));
 //BA.debugLineNum = 425;BA.debugLine="Texts.Put(\"new_note\", \"New Note\")";
_texts.Put((Object)("new_note"),(Object)("New Note"));
 //BA.debugLineNum = 426;BA.debugLine="Texts.Put(\"add_note\", \"Add note\")";
_texts.Put((Object)("add_note"),(Object)("Add note"));
 //BA.debugLineNum = 427;BA.debugLine="Texts.Put(\"edit_note\", \"Edit note\")";
_texts.Put((Object)("edit_note"),(Object)("Edit note"));
 //BA.debugLineNum = 430;BA.debugLine="Texts.Put(\"wifi_name\", \"Network name (SSID)\")";
_texts.Put((Object)("wifi_name"),(Object)("Network name (SSID)"));
 //BA.debugLineNum = 431;BA.debugLine="Texts.Put(\"wifi_password\", \"Network password\")";
_texts.Put((Object)("wifi_password"),(Object)("Network password"));
 //BA.debugLineNum = 432;BA.debugLine="Texts.Put(\"wifi_security\", \"Security type\")";
_texts.Put((Object)("wifi_security"),(Object)("Security type"));
 //BA.debugLineNum = 433;BA.debugLine="Texts.Put(\"add_wifi\", \"Add network\")";
_texts.Put((Object)("add_wifi"),(Object)("Add network"));
 //BA.debugLineNum = 436;BA.debugLine="Texts.Put(\"generator\", \"Generator\")";
_texts.Put((Object)("generator"),(Object)("Generator"));
 //BA.debugLineNum = 437;BA.debugLine="Texts.Put(\"length\", \"Length\")";
_texts.Put((Object)("length"),(Object)("Length"));
 //BA.debugLineNum = 438;BA.debugLine="Texts.Put(\"uppercase\", \"Uppercase (A-Z)\")";
_texts.Put((Object)("uppercase"),(Object)("Uppercase (A-Z)"));
 //BA.debugLineNum = 439;BA.debugLine="Texts.Put(\"lowercase\", \"Lowercase (a-z)\")";
_texts.Put((Object)("lowercase"),(Object)("Lowercase (a-z)"));
 //BA.debugLineNum = 440;BA.debugLine="Texts.Put(\"numbers\", \"Numbers (0-9)\")";
_texts.Put((Object)("numbers"),(Object)("Numbers (0-9)"));
 //BA.debugLineNum = 441;BA.debugLine="Texts.Put(\"symbols\", \"Symbols (!@#$)\")";
_texts.Put((Object)("symbols"),(Object)("Symbols (!@#$)"));
 //BA.debugLineNum = 442;BA.debugLine="Texts.Put(\"generate\", \"Generate\")";
_texts.Put((Object)("generate"),(Object)("Generate"));
 //BA.debugLineNum = 443;BA.debugLine="Texts.Put(\"use_password\", \"Use this password\")";
_texts.Put((Object)("use_password"),(Object)("Use this password"));
 //BA.debugLineNum = 446;BA.debugLine="Texts.Put(\"settings\", \"Settings\")";
_texts.Put((Object)("settings"),(Object)("Settings"));
 //BA.debugLineNum = 447;BA.debugLine="Texts.Put(\"settings_general\", \"General\")";
_texts.Put((Object)("settings_general"),(Object)("General"));
 //BA.debugLineNum = 448;BA.debugLine="Texts.Put(\"settings_security\", \"Security\")";
_texts.Put((Object)("settings_security"),(Object)("Security"));
 //BA.debugLineNum = 449;BA.debugLine="Texts.Put(\"data\", \"Data\")";
_texts.Put((Object)("data"),(Object)("Data"));
 //BA.debugLineNum = 450;BA.debugLine="Texts.Put(\"language\", \"Language\")";
_texts.Put((Object)("language"),(Object)("Language"));
 //BA.debugLineNum = 451;BA.debugLine="Texts.Put(\"theme\", \"Theme\")";
_texts.Put((Object)("theme"),(Object)("Theme"));
 //BA.debugLineNum = 452;BA.debugLine="Texts.Put(\"theme_light\", \"Light\")";
_texts.Put((Object)("theme_light"),(Object)("Light"));
 //BA.debugLineNum = 453;BA.debugLine="Texts.Put(\"theme_dark\", \"Dark\")";
_texts.Put((Object)("theme_dark"),(Object)("Dark"));
 //BA.debugLineNum = 454;BA.debugLine="Texts.Put(\"session_timeout\", \"Session timeout\")";
_texts.Put((Object)("session_timeout"),(Object)("Session timeout"));
 //BA.debugLineNum = 455;BA.debugLine="Texts.Put(\"clipboard_timeout\", \"Clear clipboard\")";
_texts.Put((Object)("clipboard_timeout"),(Object)("Clear clipboard"));
 //BA.debugLineNum = 456;BA.debugLine="Texts.Put(\"biometric\", \"Biometric\")";
_texts.Put((Object)("biometric"),(Object)("Biometric"));
 //BA.debugLineNum = 457;BA.debugLine="Texts.Put(\"use_pin\", \"Use PIN\")";
_texts.Put((Object)("use_pin"),(Object)("Use PIN"));
 //BA.debugLineNum = 458;BA.debugLine="Texts.Put(\"use_pin_desc\", \"6-digit PIN to open th";
_texts.Put((Object)("use_pin_desc"),(Object)("6-digit PIN to open the app"));
 //BA.debugLineNum = 459;BA.debugLine="Texts.Put(\"use_biometric_desc\", \"Use fingerprint";
_texts.Put((Object)("use_biometric_desc"),(Object)("Use fingerprint or face recognition"));
 //BA.debugLineNum = 460;BA.debugLine="Texts.Put(\"create_pin_msg\", \"You will be asked to";
_texts.Put((Object)("create_pin_msg"),(Object)("You will be asked to create a 6-digit PIN."));
 //BA.debugLineNum = 461;BA.debugLine="Texts.Put(\"remove_pin_msg\", \"Do you want to remov";
_texts.Put((Object)("remove_pin_msg"),(Object)("Do you want to remove the access PIN?"));
 //BA.debugLineNum = 462;BA.debugLine="Texts.Put(\"biometric_enabled\", \"Biometric enabled";
_texts.Put((Object)("biometric_enabled"),(Object)("Biometric enabled"));
 //BA.debugLineNum = 463;BA.debugLine="Texts.Put(\"biometric_disabled\", \"Biometric disabl";
_texts.Put((Object)("biometric_disabled"),(Object)("Biometric disabled"));
 //BA.debugLineNum = 464;BA.debugLine="Texts.Put(\"pin_access\", \"PIN access\")";
_texts.Put((Object)("pin_access"),(Object)("PIN access"));
 //BA.debugLineNum = 465;BA.debugLine="Texts.Put(\"change_pin\", \"Change PIN\")";
_texts.Put((Object)("change_pin"),(Object)("Change PIN"));
 //BA.debugLineNum = 466;BA.debugLine="Texts.Put(\"remove_pin\", \"Remove PIN\")";
_texts.Put((Object)("remove_pin"),(Object)("Remove PIN"));
 //BA.debugLineNum = 467;BA.debugLine="Texts.Put(\"about\", \"About\")";
_texts.Put((Object)("about"),(Object)("About"));
 //BA.debugLineNum = 468;BA.debugLine="Texts.Put(\"version\", \"Version\")";
_texts.Put((Object)("version"),(Object)("Version"));
 //BA.debugLineNum = 469;BA.debugLine="Texts.Put(\"clear_data\", \"Clear all data\")";
_texts.Put((Object)("clear_data"),(Object)("Clear all data"));
 //BA.debugLineNum = 470;BA.debugLine="Texts.Put(\"clear_data_desc\", \"Remove all password";
_texts.Put((Object)("clear_data_desc"),(Object)("Remove all passwords, groups and notes"));
 //BA.debugLineNum = 471;BA.debugLine="Texts.Put(\"clear_data_confirm\", \"WARNING: This wi";
_texts.Put((Object)("clear_data_confirm"),(Object)("WARNING: This will PERMANENTLY DELETE all your data (passwords, groups, notes). This action CANNOT be undone. Do you want to continue?"));
 //BA.debugLineNum = 472;BA.debugLine="Texts.Put(\"data_cleared\", \"All data has been dele";
_texts.Put((Object)("data_cleared"),(Object)("All data has been deleted"));
 //BA.debugLineNum = 473;BA.debugLine="Texts.Put(\"export_data\", \"Export data\")";
_texts.Put((Object)("export_data"),(Object)("Export data"));
 //BA.debugLineNum = 474;BA.debugLine="Texts.Put(\"import_data\", \"Import data\")";
_texts.Put((Object)("import_data"),(Object)("Import data"));
 //BA.debugLineNum = 475;BA.debugLine="Texts.Put(\"backup\", \"Backup\")";
_texts.Put((Object)("backup"),(Object)("Backup"));
 //BA.debugLineNum = 476;BA.debugLine="Texts.Put(\"minute\", \"minute\")";
_texts.Put((Object)("minute"),(Object)("minute"));
 //BA.debugLineNum = 477;BA.debugLine="Texts.Put(\"minutes\", \"minutes\")";
_texts.Put((Object)("minutes"),(Object)("minutes"));
 //BA.debugLineNum = 480;BA.debugLine="Texts.Put(\"confirm_delete\", \"Confirm delete\")";
_texts.Put((Object)("confirm_delete"),(Object)("Confirm delete"));
 //BA.debugLineNum = 481;BA.debugLine="Texts.Put(\"confirm_delete_msg\", \"Do you really wa";
_texts.Put((Object)("confirm_delete_msg"),(Object)("Do you really want to delete this item?"));
 //BA.debugLineNum = 482;BA.debugLine="Texts.Put(\"confirm_exit\", \"Do you want to exit?\")";
_texts.Put((Object)("confirm_exit"),(Object)("Do you want to exit?"));
 //BA.debugLineNum = 485;BA.debugLine="Texts.Put(\"onb_welcome_title\", \"Welcome to LockZe";
_texts.Put((Object)("onb_welcome_title"),(Object)("Welcome to LockZero"));
 //BA.debugLineNum = 486;BA.debugLine="Texts.Put(\"onb_welcome_text\", \"Lock and ZERO worr";
_texts.Put((Object)("onb_welcome_text"),(Object)("Lock and ZERO worries"+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"LockZero is your personal digital vault."+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"• ZERO Internet - Your data never leaves the device"+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"• ZERO Knowledge - Not even we know your phrase"+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"• ZERO Recovery - You are solely responsible"+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"• ZERO Subscription - One-time payment or free"));
 //BA.debugLineNum = 487;BA.debugLine="Texts.Put(\"onb_warning_title\", \"⚠️ IMPORTANT WARN";
_texts.Put((Object)("onb_warning_title"),(Object)("⚠️ IMPORTANT WARNING"));
 //BA.debugLineNum = 488;BA.debugLine="Texts.Put(\"onb_warning_text\", \"READ CAREFULLY:\" &";
_texts.Put((Object)("onb_warning_text"),(Object)("READ CAREFULLY:"+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"1. Your passphrase is NOT stored anywhere."+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"2. If you FORGET your passphrase, you WILL LOSE ALL YOUR DATA."+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"3. There is NO 'Forgot password'. There is NO recovery."+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"4. NOBODY can help you. Not us, not Google, nobody."+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"5. BACKUPS protect against device loss, NOT against forgetting your passphrase."+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"💡 TIP: Use a prayer, song lyric, or personal phrase you will never forget."));
 //BA.debugLineNum = 489;BA.debugLine="Texts.Put(\"onb_understand\", \"I understand there i";
_texts.Put((Object)("onb_understand"),(Object)("I understand there is NO recovery and I am solely responsible"));
 //BA.debugLineNum = 490;BA.debugLine="Texts.Put(\"onb_accept\", \"Accept and Continue\")";
_texts.Put((Object)("onb_accept"),(Object)("Accept and Continue"));
 //BA.debugLineNum = 491;BA.debugLine="Texts.Put(\"onb_setup_title\", \"Create your Passphr";
_texts.Put((Object)("onb_setup_title"),(Object)("Create your Passphrase"));
 //BA.debugLineNum = 492;BA.debugLine="Texts.Put(\"onb_setup_info\", \"This phrase will be";
_texts.Put((Object)("onb_setup_info"),(Object)("This phrase will be used to encrypt all your data. Choose something you can remember, but that is hard to guess."+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"Minimum: 8 characters"));
 //BA.debugLineNum = 493;BA.debugLine="Texts.Put(\"onb_passphrase_hint\", \"Enter your pass";
_texts.Put((Object)("onb_passphrase_hint"),(Object)("Enter your passphrase"));
 //BA.debugLineNum = 494;BA.debugLine="Texts.Put(\"onb_passphrase_confirm\", \"Confirm your";
_texts.Put((Object)("onb_passphrase_confirm"),(Object)("Confirm your passphrase"));
 //BA.debugLineNum = 495;BA.debugLine="Texts.Put(\"onb_create_continue\", \"Create and Cont";
_texts.Put((Object)("onb_create_continue"),(Object)("Create and Continue"));
 //BA.debugLineNum = 496;BA.debugLine="Texts.Put(\"onb_backup_title\", \"Optional Backup\")";
_texts.Put((Object)("onb_backup_title"),(Object)("Optional Backup"));
 //BA.debugLineNum = 497;BA.debugLine="Texts.Put(\"onb_backup_text\", \"You can create a ba";
_texts.Put((Object)("onb_backup_text"),(Object)("You can create a backup now or later in settings."+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"This backup will be protected by your passphrase."+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"Store the .lockzero file in a safe place (USB drive, computer, personal cloud)."));
 //BA.debugLineNum = 498;BA.debugLine="Texts.Put(\"onb_create_backup\", \"Create Backup Now";
_texts.Put((Object)("onb_create_backup"),(Object)("Create Backup Now"));
 //BA.debugLineNum = 499;BA.debugLine="Texts.Put(\"onb_skip_backup\", \"Skip for Now\")";
_texts.Put((Object)("onb_skip_backup"),(Object)("Skip for Now"));
 //BA.debugLineNum = 500;BA.debugLine="Texts.Put(\"onb_complete_title\", \"All Set!\")";
_texts.Put((Object)("onb_complete_title"),(Object)("All Set!"));
 //BA.debugLineNum = 501;BA.debugLine="Texts.Put(\"onb_complete_text\", \"Your LockZero is";
_texts.Put((Object)("onb_complete_text"),(Object)("Your LockZero is configured and protected."+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"Remember:"+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"• Your passphrase: NEVER forget"+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"• Backups: Do them regularly"+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"• Security: 100% in your hands"+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"Lock and ZERO worries!"));
 //BA.debugLineNum = 502;BA.debugLine="Texts.Put(\"onb_start\", \"Start Using\")";
_texts.Put((Object)("onb_start"),(Object)("Start Using"));
 //BA.debugLineNum = 503;BA.debugLine="Texts.Put(\"onb_min_chars\", \"Passphrase must have";
_texts.Put((Object)("onb_min_chars"),(Object)("Passphrase must have at least 8 characters"));
 //BA.debugLineNum = 504;BA.debugLine="Texts.Put(\"onb_not_match\", \"Passphrases do not ma";
_texts.Put((Object)("onb_not_match"),(Object)("Passphrases do not match"));
 //BA.debugLineNum = 505;BA.debugLine="Texts.Put(\"onb_must_accept\", \"You need to accept";
_texts.Put((Object)("onb_must_accept"),(Object)("You need to accept the terms"));
 //BA.debugLineNum = 506;BA.debugLine="Texts.Put(\"onb_complete_setup\", \"Complete the ini";
_texts.Put((Object)("onb_complete_setup"),(Object)("Complete the initial setup"));
 //BA.debugLineNum = 509;BA.debugLine="Texts.Put(\"error_empty_field\", \"Please fill all f";
_texts.Put((Object)("error_empty_field"),(Object)("Please fill all fields"));
 //BA.debugLineNum = 510;BA.debugLine="Texts.Put(\"error_invalid_data\", \"Invalid data\")";
_texts.Put((Object)("error_invalid_data"),(Object)("Invalid data"));
 //BA.debugLineNum = 511;BA.debugLine="Texts.Put(\"error_save\", \"Error saving\")";
_texts.Put((Object)("error_save"),(Object)("Error saving"));
 //BA.debugLineNum = 512;BA.debugLine="Texts.Put(\"error_load\", \"Error loading\")";
_texts.Put((Object)("error_load"),(Object)("Error loading"));
 //BA.debugLineNum = 515;BA.debugLine="Texts.Put(\"backup_last\", \"Last backup:\")";
_texts.Put((Object)("backup_last"),(Object)("Last backup:"));
 //BA.debugLineNum = 516;BA.debugLine="Texts.Put(\"backup_never\", \"No backup made\")";
_texts.Put((Object)("backup_never"),(Object)("No backup made"));
 //BA.debugLineNum = 517;BA.debugLine="Texts.Put(\"backup_export\", \"EXPORT\")";
_texts.Put((Object)("backup_export"),(Object)("EXPORT"));
 //BA.debugLineNum = 518;BA.debugLine="Texts.Put(\"backup_create\", \"Create Backup Now\")";
_texts.Put((Object)("backup_create"),(Object)("Create Backup Now"));
 //BA.debugLineNum = 519;BA.debugLine="Texts.Put(\"backup_create_info\", \"Creates an encry";
_texts.Put((Object)("backup_create_info"),(Object)("Creates an encrypted .lockzero file with all your data."));
 //BA.debugLineNum = 520;BA.debugLine="Texts.Put(\"backup_import\", \"IMPORT\")";
_texts.Put((Object)("backup_import"),(Object)("IMPORT"));
 //BA.debugLineNum = 521;BA.debugLine="Texts.Put(\"backup_restore\", \"Restore Backup\")";
_texts.Put((Object)("backup_restore"),(Object)("Restore Backup"));
 //BA.debugLineNum = 522;BA.debugLine="Texts.Put(\"backup_restore_info\", \"Restores data f";
_texts.Put((Object)("backup_restore_info"),(Object)("Restores data from a .lockzero file. You will need the phrase used when creating the backup."));
 //BA.debugLineNum = 523;BA.debugLine="Texts.Put(\"backup_paste\", \"Paste Backup\")";
_texts.Put((Object)("backup_paste"),(Object)("Paste Backup"));
 //BA.debugLineNum = 524;BA.debugLine="Texts.Put(\"backup_paste_instructions\", \"Open the";
_texts.Put((Object)("backup_paste_instructions"),(Object)("Open the .lockzero file in a text editor, copy all content and paste here."));
 //BA.debugLineNum = 525;BA.debugLine="Texts.Put(\"backup_paste_hint\", \"Paste the backup";
_texts.Put((Object)("backup_paste_hint"),(Object)("Paste the backup content here..."));
 //BA.debugLineNum = 526;BA.debugLine="Texts.Put(\"backup_paste_empty\", \"Paste the backup";
_texts.Put((Object)("backup_paste_empty"),(Object)("Paste the backup content"));
 //BA.debugLineNum = 527;BA.debugLine="Texts.Put(\"backup_invalid\", \"Invalid backup forma";
_texts.Put((Object)("backup_invalid"),(Object)("Invalid backup format"));
 //BA.debugLineNum = 528;BA.debugLine="Texts.Put(\"backup_verify\", \"VERIFY\")";
_texts.Put((Object)("backup_verify"),(Object)("VERIFY"));
 //BA.debugLineNum = 529;BA.debugLine="Texts.Put(\"backup_test\", \"Test Backup\")";
_texts.Put((Object)("backup_test"),(Object)("Test Backup"));
 //BA.debugLineNum = 530;BA.debugLine="Texts.Put(\"backup_test_info\", \"Checks if the back";
_texts.Put((Object)("backup_test_info"),(Object)("Checks if the backup can be opened. Does not change your current data."));
 //BA.debugLineNum = 531;BA.debugLine="Texts.Put(\"backup_tip\", \"TIP: Use a prayer, song";
_texts.Put((Object)("backup_tip"),(Object)("TIP: Use a prayer, song lyric, or phrase you already know by heart. No need to write it down!"));
 //BA.debugLineNum = 532;BA.debugLine="Texts.Put(\"backup_phrase_hint\", \"Phrase to protec";
_texts.Put((Object)("backup_phrase_hint"),(Object)("Phrase to protect the backup"));
 //BA.debugLineNum = 533;BA.debugLine="Texts.Put(\"backup_phrase_min\", \"Phrase must have";
_texts.Put((Object)("backup_phrase_min"),(Object)("Phrase must have at least 6 characters"));
 //BA.debugLineNum = 534;BA.debugLine="Texts.Put(\"backup_success\", \"Backup created succe";
_texts.Put((Object)("backup_success"),(Object)("Backup created successfully!"));
 //BA.debugLineNum = 535;BA.debugLine="Texts.Put(\"backup_saved_at\", \"Saved at:\")";
_texts.Put((Object)("backup_saved_at"),(Object)("Saved at:"));
 //BA.debugLineNum = 536;BA.debugLine="Texts.Put(\"backup_error\", \"Error creating backup\"";
_texts.Put((Object)("backup_error"),(Object)("Error creating backup"));
 //BA.debugLineNum = 537;BA.debugLine="Texts.Put(\"backup_none_found\", \"No .lockzero file";
_texts.Put((Object)("backup_none_found"),(Object)("No .lockzero file found"));
 //BA.debugLineNum = 538;BA.debugLine="Texts.Put(\"backup_phrase_backup\", \"Backup phrase\"";
_texts.Put((Object)("backup_phrase_backup"),(Object)("Backup phrase"));
 //BA.debugLineNum = 539;BA.debugLine="Texts.Put(\"backup_enter_phrase\", \"Enter the phras";
_texts.Put((Object)("backup_enter_phrase"),(Object)("Enter the phrase used when creating the backup:"));
 //BA.debugLineNum = 540;BA.debugLine="Texts.Put(\"backup_confirm_restore\", \"WARNING: Thi";
_texts.Put((Object)("backup_confirm_restore"),(Object)("WARNING: This will add the backup data to your current data."));
 //BA.debugLineNum = 541;BA.debugLine="Texts.Put(\"backup_continue\", \"Do you want to cont";
_texts.Put((Object)("backup_continue"),(Object)("Do you want to continue?"));
 //BA.debugLineNum = 542;BA.debugLine="Texts.Put(\"backup_restored\", \"Backup restored!\")";
_texts.Put((Object)("backup_restored"),(Object)("Backup restored!"));
 //BA.debugLineNum = 543;BA.debugLine="Texts.Put(\"backup_groups\", \"Groups:\")";
_texts.Put((Object)("backup_groups"),(Object)("Groups:"));
 //BA.debugLineNum = 544;BA.debugLine="Texts.Put(\"backup_entries\", \"Passwords:\")";
_texts.Put((Object)("backup_entries"),(Object)("Passwords:"));
 //BA.debugLineNum = 545;BA.debugLine="Texts.Put(\"backup_notes\", \"Notes:\")";
_texts.Put((Object)("backup_notes"),(Object)("Notes:"));
 //BA.debugLineNum = 546;BA.debugLine="Texts.Put(\"backup_valid\", \"Backup VALID!\")";
_texts.Put((Object)("backup_valid"),(Object)("Backup VALID!"));
 //BA.debugLineNum = 547;BA.debugLine="Texts.Put(\"backup_created_at\", \"Created at:\")";
_texts.Put((Object)("backup_created_at"),(Object)("Created at:"));
 //BA.debugLineNum = 548;BA.debugLine="Texts.Put(\"backup_test_ok\", \"Test OK\")";
_texts.Put((Object)("backup_test_ok"),(Object)("Test OK"));
 //BA.debugLineNum = 549;BA.debugLine="Texts.Put(\"backup_test_failed\", \"Wrong phrase or";
_texts.Put((Object)("backup_test_failed"),(Object)("Wrong phrase or corrupted file"));
 //BA.debugLineNum = 550;BA.debugLine="Texts.Put(\"backup_wrong_phrase\", \"Wrong phrase or";
_texts.Put((Object)("backup_wrong_phrase"),(Object)("Wrong phrase or corrupted file"));
 //BA.debugLineNum = 551;BA.debugLine="Texts.Put(\"backup_share_question\", \"Share the bac";
_texts.Put((Object)("backup_share_question"),(Object)("Share the backup file?"));
 //BA.debugLineNum = 552;BA.debugLine="Texts.Put(\"share\", \"Share\")";
_texts.Put((Object)("share"),(Object)("Share"));
 //BA.debugLineNum = 553;BA.debugLine="Texts.Put(\"share_error\", \"Error sharing\")";
_texts.Put((Object)("share_error"),(Object)("Error sharing"));
 //BA.debugLineNum = 554;BA.debugLine="End Sub";
return "";
}
public static String  _loadportuguese(anywheresoftware.b4a.BA _ba) throws Exception{
 //BA.debugLineNum = 57;BA.debugLine="Private Sub LoadPortuguese";
 //BA.debugLineNum = 59;BA.debugLine="Texts.Put(\"app_name\", \"LockZero\")";
_texts.Put((Object)("app_name"),(Object)("LockZero"));
 //BA.debugLineNum = 60;BA.debugLine="Texts.Put(\"app_tagline\", \"Lock and ZERO worries\")";
_texts.Put((Object)("app_tagline"),(Object)("Lock and ZERO worries"));
 //BA.debugLineNum = 61;BA.debugLine="Texts.Put(\"app_slogan\", \"Guarde suas informações";
_texts.Put((Object)("app_slogan"),(Object)("Guarde suas informações e ZERO preocupação"));
 //BA.debugLineNum = 62;BA.debugLine="Texts.Put(\"free_version\", \"Versão Gratuita\")";
_texts.Put((Object)("free_version"),(Object)("Versão Gratuita"));
 //BA.debugLineNum = 65;BA.debugLine="Texts.Put(\"ok\", \"OK\")";
_texts.Put((Object)("ok"),(Object)("OK"));
 //BA.debugLineNum = 66;BA.debugLine="Texts.Put(\"cancel\", \"Cancelar\")";
_texts.Put((Object)("cancel"),(Object)("Cancelar"));
 //BA.debugLineNum = 67;BA.debugLine="Texts.Put(\"save\", \"Salvar\")";
_texts.Put((Object)("save"),(Object)("Salvar"));
 //BA.debugLineNum = 68;BA.debugLine="Texts.Put(\"delete\", \"Excluir\")";
_texts.Put((Object)("delete"),(Object)("Excluir"));
 //BA.debugLineNum = 69;BA.debugLine="Texts.Put(\"edit\", \"Editar\")";
_texts.Put((Object)("edit"),(Object)("Editar"));
 //BA.debugLineNum = 70;BA.debugLine="Texts.Put(\"add\", \"Adicionar\")";
_texts.Put((Object)("add"),(Object)("Adicionar"));
 //BA.debugLineNum = 71;BA.debugLine="Texts.Put(\"close\", \"Fechar\")";
_texts.Put((Object)("close"),(Object)("Fechar"));
 //BA.debugLineNum = 72;BA.debugLine="Texts.Put(\"back\", \"Voltar\")";
_texts.Put((Object)("back"),(Object)("Voltar"));
 //BA.debugLineNum = 73;BA.debugLine="Texts.Put(\"next\", \"Próximo\")";
_texts.Put((Object)("next"),(Object)("Próximo"));
 //BA.debugLineNum = 74;BA.debugLine="Texts.Put(\"continue\", \"Continuar\")";
_texts.Put((Object)("continue"),(Object)("Continuar"));
 //BA.debugLineNum = 75;BA.debugLine="Texts.Put(\"done\", \"Concluído\")";
_texts.Put((Object)("done"),(Object)("Concluído"));
 //BA.debugLineNum = 76;BA.debugLine="Texts.Put(\"search\", \"Buscar\")";
_texts.Put((Object)("search"),(Object)("Buscar"));
 //BA.debugLineNum = 77;BA.debugLine="Texts.Put(\"copy\", \"Copiar\")";
_texts.Put((Object)("copy"),(Object)("Copiar"));
 //BA.debugLineNum = 78;BA.debugLine="Texts.Put(\"copied\", \"Copiado!\")";
_texts.Put((Object)("copied"),(Object)("Copiado!"));
 //BA.debugLineNum = 79;BA.debugLine="Texts.Put(\"show\", \"Mostrar\")";
_texts.Put((Object)("show"),(Object)("Mostrar"));
 //BA.debugLineNum = 80;BA.debugLine="Texts.Put(\"hide\", \"Ocultar\")";
_texts.Put((Object)("hide"),(Object)("Ocultar"));
 //BA.debugLineNum = 81;BA.debugLine="Texts.Put(\"view\", \"Ver\")";
_texts.Put((Object)("view"),(Object)("Ver"));
 //BA.debugLineNum = 82;BA.debugLine="Texts.Put(\"yes\", \"Sim\")";
_texts.Put((Object)("yes"),(Object)("Sim"));
 //BA.debugLineNum = 83;BA.debugLine="Texts.Put(\"no\", \"Não\")";
_texts.Put((Object)("no"),(Object)("Não"));
 //BA.debugLineNum = 84;BA.debugLine="Texts.Put(\"loading\", \"Carregando...\")";
_texts.Put((Object)("loading"),(Object)("Carregando..."));
 //BA.debugLineNum = 85;BA.debugLine="Texts.Put(\"empty\", \"Nenhum item\")";
_texts.Put((Object)("empty"),(Object)("Nenhum item"));
 //BA.debugLineNum = 86;BA.debugLine="Texts.Put(\"error\", \"Erro\")";
_texts.Put((Object)("error"),(Object)("Erro"));
 //BA.debugLineNum = 87;BA.debugLine="Texts.Put(\"success\", \"Sucesso\")";
_texts.Put((Object)("success"),(Object)("Sucesso"));
 //BA.debugLineNum = 88;BA.debugLine="Texts.Put(\"warning\", \"Aviso\")";
_texts.Put((Object)("warning"),(Object)("Aviso"));
 //BA.debugLineNum = 91;BA.debugLine="Texts.Put(\"enter_passphrase\", \"Digite sua frase s";
_texts.Put((Object)("enter_passphrase"),(Object)("Digite sua frase secreta"));
 //BA.debugLineNum = 92;BA.debugLine="Texts.Put(\"passphrase_hint\", \"Sua frase pessoal..";
_texts.Put((Object)("passphrase_hint"),(Object)("Sua frase pessoal..."));
 //BA.debugLineNum = 93;BA.debugLine="Texts.Put(\"passphrase_min_8\", \"Frase deve ter no";
_texts.Put((Object)("passphrase_min_8"),(Object)("Frase deve ter no mínimo 8 caracteres"));
 //BA.debugLineNum = 94;BA.debugLine="Texts.Put(\"passphrase_too_short\", \"Frase muito cu";
_texts.Put((Object)("passphrase_too_short"),(Object)("Frase muito curta"));
 //BA.debugLineNum = 95;BA.debugLine="Texts.Put(\"confirm\", \"Confirmar\")";
_texts.Put((Object)("confirm"),(Object)("Confirmar"));
 //BA.debugLineNum = 96;BA.debugLine="Texts.Put(\"unlock\", \"Desbloquear\")";
_texts.Put((Object)("unlock"),(Object)("Desbloquear"));
 //BA.debugLineNum = 97;BA.debugLine="Texts.Put(\"use_biometric\", \"Usar biometria\")";
_texts.Put((Object)("use_biometric"),(Object)("Usar biometria"));
 //BA.debugLineNum = 98;BA.debugLine="Texts.Put(\"wrong_passphrase\", \"Frase incorreta\")";
_texts.Put((Object)("wrong_passphrase"),(Object)("Frase incorreta"));
 //BA.debugLineNum = 99;BA.debugLine="Texts.Put(\"session_expired\", \"Sessão expirada\")";
_texts.Put((Object)("session_expired"),(Object)("Sessão expirada"));
 //BA.debugLineNum = 100;BA.debugLine="Texts.Put(\"session_remaining\", \"Sessão expira em\"";
_texts.Put((Object)("session_remaining"),(Object)("Sessão expira em"));
 //BA.debugLineNum = 101;BA.debugLine="Texts.Put(\"wait_timeout\", \"Aguarde\")";
_texts.Put((Object)("wait_timeout"),(Object)("Aguarde"));
 //BA.debugLineNum = 102;BA.debugLine="Texts.Put(\"attempts\", \"tentativas\")";
_texts.Put((Object)("attempts"),(Object)("tentativas"));
 //BA.debugLineNum = 103;BA.debugLine="Texts.Put(\"failed_attempts\", \"tentativas incorret";
_texts.Put((Object)("failed_attempts"),(Object)("tentativas incorretas"));
 //BA.debugLineNum = 104;BA.debugLine="Texts.Put(\"lock\", \"Bloquear\")";
_texts.Put((Object)("lock"),(Object)("Bloquear"));
 //BA.debugLineNum = 105;BA.debugLine="Texts.Put(\"lock_confirm_msg\", \"Deseja bloquear a";
_texts.Put((Object)("lock_confirm_msg"),(Object)("Deseja bloquear a sessão agora?"));
 //BA.debugLineNum = 106;BA.debugLine="Texts.Put(\"locked\", \"Sessão bloqueada\")";
_texts.Put((Object)("locked"),(Object)("Sessão bloqueada"));
 //BA.debugLineNum = 109;BA.debugLine="Texts.Put(\"passphrase_mode\", \"Modo de frase-senha";
_texts.Put((Object)("passphrase_mode"),(Object)("Modo de frase-senha"));
 //BA.debugLineNum = 110;BA.debugLine="Texts.Put(\"single_passphrase\", \"Frase única\")";
_texts.Put((Object)("single_passphrase"),(Object)("Frase única"));
 //BA.debugLineNum = 111;BA.debugLine="Texts.Put(\"single_passphrase_desc\", \"Usar a mesma";
_texts.Put((Object)("single_passphrase_desc"),(Object)("Usar a mesma frase para todas as categorias"));
 //BA.debugLineNum = 112;BA.debugLine="Texts.Put(\"multi_passphrase\", \"Frase por categori";
_texts.Put((Object)("multi_passphrase"),(Object)("Frase por categoria"));
 //BA.debugLineNum = 113;BA.debugLine="Texts.Put(\"multi_passphrase_desc\", \"Cada categori";
_texts.Put((Object)("multi_passphrase_desc"),(Object)("Cada categoria pode ter sua própria frase"));
 //BA.debugLineNum = 116;BA.debugLine="Texts.Put(\"passwords\", \"Senhas\")";
_texts.Put((Object)("passwords"),(Object)("Senhas"));
 //BA.debugLineNum = 117;BA.debugLine="Texts.Put(\"cards\", \"Cartões\")";
_texts.Put((Object)("cards"),(Object)("Cartões"));
 //BA.debugLineNum = 118;BA.debugLine="Texts.Put(\"documents\", \"Documentos\")";
_texts.Put((Object)("documents"),(Object)("Documentos"));
 //BA.debugLineNum = 119;BA.debugLine="Texts.Put(\"notes\", \"Notas\")";
_texts.Put((Object)("notes"),(Object)("Notas"));
 //BA.debugLineNum = 120;BA.debugLine="Texts.Put(\"wifi\", \"Wi-Fi\")";
_texts.Put((Object)("wifi"),(Object)("Wi-Fi"));
 //BA.debugLineNum = 123;BA.debugLine="Texts.Put(\"onb_welcome_title\", \"Bem-vindo ao Lock";
_texts.Put((Object)("onb_welcome_title"),(Object)("Bem-vindo ao LockZero"));
 //BA.debugLineNum = 124;BA.debugLine="Texts.Put(\"onb_welcome_text\", \"Lock and ZERO worr";
_texts.Put((Object)("onb_welcome_text"),(Object)("Lock and ZERO worries"+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"O LockZero é seu cofre digital pessoal."+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"• ZERO Internet - Seus dados nunca saem do dispositivo"+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"• ZERO Conhecimento - Nem nós sabemos sua frase"+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"• ZERO Recuperação - Você é o único responsável"+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"• Sem mensalidades - Grátis para sempre"));
 //BA.debugLineNum = 125;BA.debugLine="Texts.Put(\"onb_warning_title\", \"⚠️ AVISO IMPORTAN";
_texts.Put((Object)("onb_warning_title"),(Object)("⚠️ AVISO IMPORTANTE"));
 //BA.debugLineNum = 126;BA.debugLine="Texts.Put(\"onb_warning_text\", \"LEIA COM ATENÇÃO:\"";
_texts.Put((Object)("onb_warning_text"),(Object)("LEIA COM ATENÇÃO:"+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"1. Sua frase-senha NÃO é armazenada em nenhum lugar."+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"2. Se você ESQUECER sua frase-senha, PERDERÁ TODOS OS SEUS DADOS."+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"3. NÃO existe 'Esqueci minha senha'. NÃO existe recuperação."+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"4. NINGUÉM pode ajudar você. Nem nós, nem a Google, nem ninguém."+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"5. BACKUPS protegem contra perda do dispositivo, NÃO contra esquecer a frase-senha."+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"💡 DICA: Use uma oração, trecho de música ou frase pessoal que você nunca vai esquecer."));
 //BA.debugLineNum = 127;BA.debugLine="Texts.Put(\"onb_understand\", \"Eu entendo que NÃO h";
_texts.Put((Object)("onb_understand"),(Object)("Eu entendo que NÃO há recuperação e sou o único responsável"));
 //BA.debugLineNum = 128;BA.debugLine="Texts.Put(\"onb_accept\", \"Aceitar e Continuar\")";
_texts.Put((Object)("onb_accept"),(Object)("Aceitar e Continuar"));
 //BA.debugLineNum = 129;BA.debugLine="Texts.Put(\"onb_setup_title\", \"Crie sua Frase-Senh";
_texts.Put((Object)("onb_setup_title"),(Object)("Crie sua Frase-Senha"));
 //BA.debugLineNum = 130;BA.debugLine="Texts.Put(\"onb_setup_info\", \"Esta frase será usad";
_texts.Put((Object)("onb_setup_info"),(Object)("Esta frase será usada para criptografar todos os seus dados. Escolha algo que você possa lembrar, mas que seja difícil de adivinhar."+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"Mínimo: 8 caracteres"));
 //BA.debugLineNum = 131;BA.debugLine="Texts.Put(\"onb_passphrase_hint\", \"Digite sua fras";
_texts.Put((Object)("onb_passphrase_hint"),(Object)("Digite sua frase-senha"));
 //BA.debugLineNum = 132;BA.debugLine="Texts.Put(\"onb_passphrase_confirm\", \"Confirme sua";
_texts.Put((Object)("onb_passphrase_confirm"),(Object)("Confirme sua frase-senha"));
 //BA.debugLineNum = 133;BA.debugLine="Texts.Put(\"onb_create_continue\", \"Criar e Continu";
_texts.Put((Object)("onb_create_continue"),(Object)("Criar e Continuar"));
 //BA.debugLineNum = 134;BA.debugLine="Texts.Put(\"onb_backup_title\", \"Backup Opcional\")";
_texts.Put((Object)("onb_backup_title"),(Object)("Backup Opcional"));
 //BA.debugLineNum = 135;BA.debugLine="Texts.Put(\"onb_backup_text\", \"Você pode criar um";
_texts.Put((Object)("onb_backup_text"),(Object)("Você pode criar um backup agora ou depois nas configurações."+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"Este backup será protegido pela sua frase-senha."+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"Guarde o arquivo .lockzero em local seguro (pendrive, computador, nuvem pessoal)."));
 //BA.debugLineNum = 136;BA.debugLine="Texts.Put(\"onb_create_backup\", \"Criar Backup Agor";
_texts.Put((Object)("onb_create_backup"),(Object)("Criar Backup Agora"));
 //BA.debugLineNum = 137;BA.debugLine="Texts.Put(\"onb_skip_backup\", \"Pular por Agora\")";
_texts.Put((Object)("onb_skip_backup"),(Object)("Pular por Agora"));
 //BA.debugLineNum = 138;BA.debugLine="Texts.Put(\"onb_complete_title\", \"Tudo Pronto!\")";
_texts.Put((Object)("onb_complete_title"),(Object)("Tudo Pronto!"));
 //BA.debugLineNum = 139;BA.debugLine="Texts.Put(\"onb_complete_text\", \"Seu LockZero está";
_texts.Put((Object)("onb_complete_text"),(Object)("Seu LockZero está configurado e protegido."+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"Lembre-se:"+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"• Sua frase-senha: NUNCA esqueça"+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"• Backups: Faça regularmente"+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"• Segurança: 100% em suas mãos"+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"Lock and ZERO worries!"+BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Chr((int) (10)))+"(Tranque e ZERO preocupação!)"));
 //BA.debugLineNum = 140;BA.debugLine="Texts.Put(\"onb_start\", \"Começar a Usar\")";
_texts.Put((Object)("onb_start"),(Object)("Começar a Usar"));
 //BA.debugLineNum = 141;BA.debugLine="Texts.Put(\"onb_min_chars\", \"Frase-senha deve ter";
_texts.Put((Object)("onb_min_chars"),(Object)("Frase-senha deve ter no mínimo 8 caracteres"));
 //BA.debugLineNum = 142;BA.debugLine="Texts.Put(\"onb_not_match\", \"As frases-senha não c";
_texts.Put((Object)("onb_not_match"),(Object)("As frases-senha não conferem"));
 //BA.debugLineNum = 143;BA.debugLine="Texts.Put(\"onb_must_accept\", \"Você precisa aceita";
_texts.Put((Object)("onb_must_accept"),(Object)("Você precisa aceitar os termos"));
 //BA.debugLineNum = 144;BA.debugLine="Texts.Put(\"onb_complete_setup\", \"Complete a confi";
_texts.Put((Object)("onb_complete_setup"),(Object)("Complete a configuração inicial"));
 //BA.debugLineNum = 147;BA.debugLine="Texts.Put(\"new_group\", \"Novo Grupo\")";
_texts.Put((Object)("new_group"),(Object)("Novo Grupo"));
 //BA.debugLineNum = 148;BA.debugLine="Texts.Put(\"edit_group\", \"Editar Grupo\")";
_texts.Put((Object)("edit_group"),(Object)("Editar Grupo"));
 //BA.debugLineNum = 149;BA.debugLine="Texts.Put(\"group_name_hint\", \"Nome do grupo\")";
_texts.Put((Object)("group_name_hint"),(Object)("Nome do grupo"));
 //BA.debugLineNum = 152;BA.debugLine="Texts.Put(\"password\", \"Senha\")";
_texts.Put((Object)("password"),(Object)("Senha"));
 //BA.debugLineNum = 153;BA.debugLine="Texts.Put(\"username\", \"Usuário\")";
_texts.Put((Object)("username"),(Object)("Usuário"));
 //BA.debugLineNum = 154;BA.debugLine="Texts.Put(\"url\", \"URL/Site\")";
_texts.Put((Object)("url"),(Object)("URL/Site"));
 //BA.debugLineNum = 155;BA.debugLine="Texts.Put(\"site_name\", \"Nome do site\")";
_texts.Put((Object)("site_name"),(Object)("Nome do site"));
 //BA.debugLineNum = 156;BA.debugLine="Texts.Put(\"site_name_hint\", \"Ex: Google, Facebook";
_texts.Put((Object)("site_name_hint"),(Object)("Ex: Google, Facebook..."));
 //BA.debugLineNum = 157;BA.debugLine="Texts.Put(\"username_hint\", \"Email ou usuário\")";
_texts.Put((Object)("username_hint"),(Object)("Email ou usuário"));
 //BA.debugLineNum = 158;BA.debugLine="Texts.Put(\"password_hint\", \"Senha\")";
_texts.Put((Object)("password_hint"),(Object)("Senha"));
 //BA.debugLineNum = 159;BA.debugLine="Texts.Put(\"notes_hint\", \"Observações (opcional)\")";
_texts.Put((Object)("notes_hint"),(Object)("Observações (opcional)"));
 //BA.debugLineNum = 160;BA.debugLine="Texts.Put(\"favorite\", \"Favorito\")";
_texts.Put((Object)("favorite"),(Object)("Favorito"));
 //BA.debugLineNum = 161;BA.debugLine="Texts.Put(\"new_password\", \"Nova Senha\")";
_texts.Put((Object)("new_password"),(Object)("Nova Senha"));
 //BA.debugLineNum = 162;BA.debugLine="Texts.Put(\"add_password\", \"Adicionar senha\")";
_texts.Put((Object)("add_password"),(Object)("Adicionar senha"));
 //BA.debugLineNum = 163;BA.debugLine="Texts.Put(\"edit_password\", \"Editar senha\")";
_texts.Put((Object)("edit_password"),(Object)("Editar senha"));
 //BA.debugLineNum = 164;BA.debugLine="Texts.Put(\"password_copied\", \"Senha copiada!\")";
_texts.Put((Object)("password_copied"),(Object)("Senha copiada!"));
 //BA.debugLineNum = 165;BA.debugLine="Texts.Put(\"clipboard_clear\", \"Clipboard limpo\")";
_texts.Put((Object)("clipboard_clear"),(Object)("Clipboard limpo"));
 //BA.debugLineNum = 166;BA.debugLine="Texts.Put(\"seconds\", \"segundos\")";
_texts.Put((Object)("seconds"),(Object)("segundos"));
 //BA.debugLineNum = 167;BA.debugLine="Texts.Put(\"generate_password\", \"Gerar senha\")";
_texts.Put((Object)("generate_password"),(Object)("Gerar senha"));
 //BA.debugLineNum = 168;BA.debugLine="Texts.Put(\"password_strength\", \"Força da senha\")";
_texts.Put((Object)("password_strength"),(Object)("Força da senha"));
 //BA.debugLineNum = 169;BA.debugLine="Texts.Put(\"weak\", \"Fraca\")";
_texts.Put((Object)("weak"),(Object)("Fraca"));
 //BA.debugLineNum = 170;BA.debugLine="Texts.Put(\"medium\", \"Média\")";
_texts.Put((Object)("medium"),(Object)("Média"));
 //BA.debugLineNum = 171;BA.debugLine="Texts.Put(\"strong\", \"Forte\")";
_texts.Put((Object)("strong"),(Object)("Forte"));
 //BA.debugLineNum = 172;BA.debugLine="Texts.Put(\"very_strong\", \"Muito forte\")";
_texts.Put((Object)("very_strong"),(Object)("Muito forte"));
 //BA.debugLineNum = 175;BA.debugLine="Texts.Put(\"card\", \"Cartão\")";
_texts.Put((Object)("card"),(Object)("Cartão"));
 //BA.debugLineNum = 176;BA.debugLine="Texts.Put(\"card_number\", \"Número do cartão\")";
_texts.Put((Object)("card_number"),(Object)("Número do cartão"));
 //BA.debugLineNum = 177;BA.debugLine="Texts.Put(\"card_holder\", \"Nome no cartão\")";
_texts.Put((Object)("card_holder"),(Object)("Nome no cartão"));
 //BA.debugLineNum = 178;BA.debugLine="Texts.Put(\"expiry_date\", \"Validade\")";
_texts.Put((Object)("expiry_date"),(Object)("Validade"));
 //BA.debugLineNum = 179;BA.debugLine="Texts.Put(\"cvv\", \"CVV\")";
_texts.Put((Object)("cvv"),(Object)("CVV"));
 //BA.debugLineNum = 180;BA.debugLine="Texts.Put(\"card_nickname\", \"Apelido do cartão\")";
_texts.Put((Object)("card_nickname"),(Object)("Apelido do cartão"));
 //BA.debugLineNum = 181;BA.debugLine="Texts.Put(\"add_card\", \"Adicionar cartão\")";
_texts.Put((Object)("add_card"),(Object)("Adicionar cartão"));
 //BA.debugLineNum = 182;BA.debugLine="Texts.Put(\"edit_card\", \"Editar cartão\")";
_texts.Put((Object)("edit_card"),(Object)("Editar cartão"));
 //BA.debugLineNum = 185;BA.debugLine="Texts.Put(\"document\", \"Documento\")";
_texts.Put((Object)("document"),(Object)("Documento"));
 //BA.debugLineNum = 186;BA.debugLine="Texts.Put(\"document_type\", \"Tipo de documento\")";
_texts.Put((Object)("document_type"),(Object)("Tipo de documento"));
 //BA.debugLineNum = 187;BA.debugLine="Texts.Put(\"add_document\", \"Adicionar documento\")";
_texts.Put((Object)("add_document"),(Object)("Adicionar documento"));
 //BA.debugLineNum = 188;BA.debugLine="Texts.Put(\"take_photo\", \"Tirar foto\")";
_texts.Put((Object)("take_photo"),(Object)("Tirar foto"));
 //BA.debugLineNum = 189;BA.debugLine="Texts.Put(\"choose_photo\", \"Escolher da galeria\")";
_texts.Put((Object)("choose_photo"),(Object)("Escolher da galeria"));
 //BA.debugLineNum = 190;BA.debugLine="Texts.Put(\"doc_cpf\", \"CPF\")";
_texts.Put((Object)("doc_cpf"),(Object)("CPF"));
 //BA.debugLineNum = 191;BA.debugLine="Texts.Put(\"doc_rg\", \"RG\")";
_texts.Put((Object)("doc_rg"),(Object)("RG"));
 //BA.debugLineNum = 192;BA.debugLine="Texts.Put(\"doc_cnh\", \"CNH\")";
_texts.Put((Object)("doc_cnh"),(Object)("CNH"));
 //BA.debugLineNum = 193;BA.debugLine="Texts.Put(\"doc_passport\", \"Passaporte\")";
_texts.Put((Object)("doc_passport"),(Object)("Passaporte"));
 //BA.debugLineNum = 194;BA.debugLine="Texts.Put(\"doc_other\", \"Outro\")";
_texts.Put((Object)("doc_other"),(Object)("Outro"));
 //BA.debugLineNum = 197;BA.debugLine="Texts.Put(\"note\", \"Nota\")";
_texts.Put((Object)("note"),(Object)("Nota"));
 //BA.debugLineNum = 198;BA.debugLine="Texts.Put(\"note_title\", \"Título\")";
_texts.Put((Object)("note_title"),(Object)("Título"));
 //BA.debugLineNum = 199;BA.debugLine="Texts.Put(\"note_content\", \"Conteúdo\")";
_texts.Put((Object)("note_content"),(Object)("Conteúdo"));
 //BA.debugLineNum = 200;BA.debugLine="Texts.Put(\"new_note\", \"Nova Nota\")";
_texts.Put((Object)("new_note"),(Object)("Nova Nota"));
 //BA.debugLineNum = 201;BA.debugLine="Texts.Put(\"add_note\", \"Adicionar nota\")";
_texts.Put((Object)("add_note"),(Object)("Adicionar nota"));
 //BA.debugLineNum = 202;BA.debugLine="Texts.Put(\"edit_note\", \"Editar nota\")";
_texts.Put((Object)("edit_note"),(Object)("Editar nota"));
 //BA.debugLineNum = 205;BA.debugLine="Texts.Put(\"wifi_name\", \"Nome da rede (SSID)\")";
_texts.Put((Object)("wifi_name"),(Object)("Nome da rede (SSID)"));
 //BA.debugLineNum = 206;BA.debugLine="Texts.Put(\"wifi_password\", \"Senha da rede\")";
_texts.Put((Object)("wifi_password"),(Object)("Senha da rede"));
 //BA.debugLineNum = 207;BA.debugLine="Texts.Put(\"wifi_security\", \"Tipo de segurança\")";
_texts.Put((Object)("wifi_security"),(Object)("Tipo de segurança"));
 //BA.debugLineNum = 208;BA.debugLine="Texts.Put(\"add_wifi\", \"Adicionar rede\")";
_texts.Put((Object)("add_wifi"),(Object)("Adicionar rede"));
 //BA.debugLineNum = 211;BA.debugLine="Texts.Put(\"generator\", \"Gerador\")";
_texts.Put((Object)("generator"),(Object)("Gerador"));
 //BA.debugLineNum = 212;BA.debugLine="Texts.Put(\"length\", \"Tamanho\")";
_texts.Put((Object)("length"),(Object)("Tamanho"));
 //BA.debugLineNum = 213;BA.debugLine="Texts.Put(\"uppercase\", \"Maiúsculas (A-Z)\")";
_texts.Put((Object)("uppercase"),(Object)("Maiúsculas (A-Z)"));
 //BA.debugLineNum = 214;BA.debugLine="Texts.Put(\"lowercase\", \"Minúsculas (a-z)\")";
_texts.Put((Object)("lowercase"),(Object)("Minúsculas (a-z)"));
 //BA.debugLineNum = 215;BA.debugLine="Texts.Put(\"numbers\", \"Números (0-9)\")";
_texts.Put((Object)("numbers"),(Object)("Números (0-9)"));
 //BA.debugLineNum = 216;BA.debugLine="Texts.Put(\"symbols\", \"Símbolos (!@#$)\")";
_texts.Put((Object)("symbols"),(Object)("Símbolos (!@#$)"));
 //BA.debugLineNum = 217;BA.debugLine="Texts.Put(\"generate\", \"Gerar\")";
_texts.Put((Object)("generate"),(Object)("Gerar"));
 //BA.debugLineNum = 218;BA.debugLine="Texts.Put(\"use_password\", \"Usar esta senha\")";
_texts.Put((Object)("use_password"),(Object)("Usar esta senha"));
 //BA.debugLineNum = 221;BA.debugLine="Texts.Put(\"settings\", \"Configurações\")";
_texts.Put((Object)("settings"),(Object)("Configurações"));
 //BA.debugLineNum = 222;BA.debugLine="Texts.Put(\"settings_general\", \"Geral\")";
_texts.Put((Object)("settings_general"),(Object)("Geral"));
 //BA.debugLineNum = 223;BA.debugLine="Texts.Put(\"settings_security\", \"Segurança\")";
_texts.Put((Object)("settings_security"),(Object)("Segurança"));
 //BA.debugLineNum = 224;BA.debugLine="Texts.Put(\"data\", \"Dados\")";
_texts.Put((Object)("data"),(Object)("Dados"));
 //BA.debugLineNum = 225;BA.debugLine="Texts.Put(\"language\", \"Idioma\")";
_texts.Put((Object)("language"),(Object)("Idioma"));
 //BA.debugLineNum = 226;BA.debugLine="Texts.Put(\"theme\", \"Tema\")";
_texts.Put((Object)("theme"),(Object)("Tema"));
 //BA.debugLineNum = 227;BA.debugLine="Texts.Put(\"theme_light\", \"Claro\")";
_texts.Put((Object)("theme_light"),(Object)("Claro"));
 //BA.debugLineNum = 228;BA.debugLine="Texts.Put(\"theme_dark\", \"Escuro\")";
_texts.Put((Object)("theme_dark"),(Object)("Escuro"));
 //BA.debugLineNum = 229;BA.debugLine="Texts.Put(\"session_timeout\", \"Tempo de sessão\")";
_texts.Put((Object)("session_timeout"),(Object)("Tempo de sessão"));
 //BA.debugLineNum = 230;BA.debugLine="Texts.Put(\"clipboard_timeout\", \"Limpar clipboard\"";
_texts.Put((Object)("clipboard_timeout"),(Object)("Limpar clipboard"));
 //BA.debugLineNum = 231;BA.debugLine="Texts.Put(\"biometric\", \"Biometria\")";
_texts.Put((Object)("biometric"),(Object)("Biometria"));
 //BA.debugLineNum = 232;BA.debugLine="Texts.Put(\"use_pin\", \"Usar PIN\")";
_texts.Put((Object)("use_pin"),(Object)("Usar PIN"));
 //BA.debugLineNum = 233;BA.debugLine="Texts.Put(\"use_pin_desc\", \"PIN de 6 dígitos para";
_texts.Put((Object)("use_pin_desc"),(Object)("PIN de 6 dígitos para abrir o app"));
 //BA.debugLineNum = 234;BA.debugLine="Texts.Put(\"use_biometric_desc\", \"Usar impressão d";
_texts.Put((Object)("use_biometric_desc"),(Object)("Usar impressão digital ou reconhecimento facial"));
 //BA.debugLineNum = 235;BA.debugLine="Texts.Put(\"create_pin_msg\", \"Você será solicitado";
_texts.Put((Object)("create_pin_msg"),(Object)("Você será solicitado a criar um PIN de 6 dígitos."));
 //BA.debugLineNum = 236;BA.debugLine="Texts.Put(\"remove_pin_msg\", \"Deseja remover o PIN";
_texts.Put((Object)("remove_pin_msg"),(Object)("Deseja remover o PIN de acesso?"));
 //BA.debugLineNum = 237;BA.debugLine="Texts.Put(\"biometric_enabled\", \"Biometria ativada";
_texts.Put((Object)("biometric_enabled"),(Object)("Biometria ativada"));
 //BA.debugLineNum = 238;BA.debugLine="Texts.Put(\"biometric_disabled\", \"Biometria desati";
_texts.Put((Object)("biometric_disabled"),(Object)("Biometria desativada"));
 //BA.debugLineNum = 239;BA.debugLine="Texts.Put(\"pin_access\", \"PIN de acesso\")";
_texts.Put((Object)("pin_access"),(Object)("PIN de acesso"));
 //BA.debugLineNum = 240;BA.debugLine="Texts.Put(\"change_pin\", \"Alterar PIN\")";
_texts.Put((Object)("change_pin"),(Object)("Alterar PIN"));
 //BA.debugLineNum = 241;BA.debugLine="Texts.Put(\"remove_pin\", \"Remover PIN\")";
_texts.Put((Object)("remove_pin"),(Object)("Remover PIN"));
 //BA.debugLineNum = 242;BA.debugLine="Texts.Put(\"about\", \"Sobre\")";
_texts.Put((Object)("about"),(Object)("Sobre"));
 //BA.debugLineNum = 243;BA.debugLine="Texts.Put(\"version\", \"Versão\")";
_texts.Put((Object)("version"),(Object)("Versão"));
 //BA.debugLineNum = 244;BA.debugLine="Texts.Put(\"clear_data\", \"Limpar todos os dados\")";
_texts.Put((Object)("clear_data"),(Object)("Limpar todos os dados"));
 //BA.debugLineNum = 245;BA.debugLine="Texts.Put(\"clear_data_desc\", \"Remove todas as sen";
_texts.Put((Object)("clear_data_desc"),(Object)("Remove todas as senhas, grupos e notas"));
 //BA.debugLineNum = 246;BA.debugLine="Texts.Put(\"clear_data_confirm\", \"ATENÇÃO: Isso ir";
_texts.Put((Object)("clear_data_confirm"),(Object)("ATENÇÃO: Isso irá APAGAR PERMANENTEMENTE todos os seus dados (senhas, grupos, notas). Esta ação NÃO pode ser desfeita. Deseja continuar?"));
 //BA.debugLineNum = 247;BA.debugLine="Texts.Put(\"data_cleared\", \"Todos os dados foram a";
_texts.Put((Object)("data_cleared"),(Object)("Todos os dados foram apagados"));
 //BA.debugLineNum = 248;BA.debugLine="Texts.Put(\"export_data\", \"Exportar dados\")";
_texts.Put((Object)("export_data"),(Object)("Exportar dados"));
 //BA.debugLineNum = 249;BA.debugLine="Texts.Put(\"import_data\", \"Importar dados\")";
_texts.Put((Object)("import_data"),(Object)("Importar dados"));
 //BA.debugLineNum = 250;BA.debugLine="Texts.Put(\"backup\", \"Backup\")";
_texts.Put((Object)("backup"),(Object)("Backup"));
 //BA.debugLineNum = 251;BA.debugLine="Texts.Put(\"minute\", \"minuto\")";
_texts.Put((Object)("minute"),(Object)("minuto"));
 //BA.debugLineNum = 252;BA.debugLine="Texts.Put(\"minutes\", \"minutos\")";
_texts.Put((Object)("minutes"),(Object)("minutos"));
 //BA.debugLineNum = 255;BA.debugLine="Texts.Put(\"confirm_delete\", \"Confirmar exclusão\")";
_texts.Put((Object)("confirm_delete"),(Object)("Confirmar exclusão"));
 //BA.debugLineNum = 256;BA.debugLine="Texts.Put(\"confirm_delete_msg\", \"Deseja realmente";
_texts.Put((Object)("confirm_delete_msg"),(Object)("Deseja realmente excluir este item?"));
 //BA.debugLineNum = 257;BA.debugLine="Texts.Put(\"confirm_exit\", \"Deseja sair?\")";
_texts.Put((Object)("confirm_exit"),(Object)("Deseja sair?"));
 //BA.debugLineNum = 260;BA.debugLine="Texts.Put(\"error_empty_field\", \"Preencha todos os";
_texts.Put((Object)("error_empty_field"),(Object)("Preencha todos os campos"));
 //BA.debugLineNum = 261;BA.debugLine="Texts.Put(\"error_invalid_data\", \"Dados inválidos\"";
_texts.Put((Object)("error_invalid_data"),(Object)("Dados inválidos"));
 //BA.debugLineNum = 262;BA.debugLine="Texts.Put(\"error_save\", \"Erro ao salvar\")";
_texts.Put((Object)("error_save"),(Object)("Erro ao salvar"));
 //BA.debugLineNum = 263;BA.debugLine="Texts.Put(\"error_load\", \"Erro ao carregar\")";
_texts.Put((Object)("error_load"),(Object)("Erro ao carregar"));
 //BA.debugLineNum = 266;BA.debugLine="Texts.Put(\"backup_last\", \"Último backup:\")";
_texts.Put((Object)("backup_last"),(Object)("Último backup:"));
 //BA.debugLineNum = 267;BA.debugLine="Texts.Put(\"backup_never\", \"Nenhum backup realizad";
_texts.Put((Object)("backup_never"),(Object)("Nenhum backup realizado"));
 //BA.debugLineNum = 268;BA.debugLine="Texts.Put(\"backup_export\", \"EXPORTAR\")";
_texts.Put((Object)("backup_export"),(Object)("EXPORTAR"));
 //BA.debugLineNum = 269;BA.debugLine="Texts.Put(\"backup_create\", \"Criar Backup Agora\")";
_texts.Put((Object)("backup_create"),(Object)("Criar Backup Agora"));
 //BA.debugLineNum = 270;BA.debugLine="Texts.Put(\"backup_create_info\", \"Cria um arquivo";
_texts.Put((Object)("backup_create_info"),(Object)("Cria um arquivo .lockzero criptografado com todos os seus dados."));
 //BA.debugLineNum = 271;BA.debugLine="Texts.Put(\"backup_import\", \"IMPORTAR\")";
_texts.Put((Object)("backup_import"),(Object)("IMPORTAR"));
 //BA.debugLineNum = 272;BA.debugLine="Texts.Put(\"backup_restore\", \"Restaurar Backup\")";
_texts.Put((Object)("backup_restore"),(Object)("Restaurar Backup"));
 //BA.debugLineNum = 273;BA.debugLine="Texts.Put(\"backup_restore_info\", \"Restaura dados";
_texts.Put((Object)("backup_restore_info"),(Object)("Restaura dados de um arquivo .lockzero. Você precisará da frase usada ao criar o backup."));
 //BA.debugLineNum = 274;BA.debugLine="Texts.Put(\"backup_paste\", \"Colar Backup\")";
_texts.Put((Object)("backup_paste"),(Object)("Colar Backup"));
 //BA.debugLineNum = 275;BA.debugLine="Texts.Put(\"backup_paste_instructions\", \"Abra o ar";
_texts.Put((Object)("backup_paste_instructions"),(Object)("Abra o arquivo .lockzero em um editor de texto, copie todo o conteúdo e cole aqui."));
 //BA.debugLineNum = 276;BA.debugLine="Texts.Put(\"backup_paste_hint\", \"Cole aqui o conte";
_texts.Put((Object)("backup_paste_hint"),(Object)("Cole aqui o conteúdo do backup..."));
 //BA.debugLineNum = 277;BA.debugLine="Texts.Put(\"backup_paste_empty\", \"Cole o conteúdo";
_texts.Put((Object)("backup_paste_empty"),(Object)("Cole o conteúdo do backup"));
 //BA.debugLineNum = 278;BA.debugLine="Texts.Put(\"backup_invalid\", \"Formato de backup in";
_texts.Put((Object)("backup_invalid"),(Object)("Formato de backup inválido"));
 //BA.debugLineNum = 279;BA.debugLine="Texts.Put(\"backup_verify\", \"VERIFICAR\")";
_texts.Put((Object)("backup_verify"),(Object)("VERIFICAR"));
 //BA.debugLineNum = 280;BA.debugLine="Texts.Put(\"backup_test\", \"Testar Backup\")";
_texts.Put((Object)("backup_test"),(Object)("Testar Backup"));
 //BA.debugLineNum = 281;BA.debugLine="Texts.Put(\"backup_test_info\", \"Verifica se o back";
_texts.Put((Object)("backup_test_info"),(Object)("Verifica se o backup pode ser aberto. Não altera seus dados atuais."));
 //BA.debugLineNum = 282;BA.debugLine="Texts.Put(\"backup_tip\", \"DICA: Use uma oração, tr";
_texts.Put((Object)("backup_tip"),(Object)("DICA: Use uma oração, trecho de música ou frase que você já conhece de cor. Assim não precisa anotar!"));
 //BA.debugLineNum = 283;BA.debugLine="Texts.Put(\"backup_phrase_hint\", \"Frase para prote";
_texts.Put((Object)("backup_phrase_hint"),(Object)("Frase para proteger o backup"));
 //BA.debugLineNum = 284;BA.debugLine="Texts.Put(\"backup_phrase_min\", \"Frase deve ter no";
_texts.Put((Object)("backup_phrase_min"),(Object)("Frase deve ter no mínimo 6 caracteres"));
 //BA.debugLineNum = 285;BA.debugLine="Texts.Put(\"backup_success\", \"Backup criado com su";
_texts.Put((Object)("backup_success"),(Object)("Backup criado com sucesso!"));
 //BA.debugLineNum = 286;BA.debugLine="Texts.Put(\"backup_saved_at\", \"Salvo em:\")";
_texts.Put((Object)("backup_saved_at"),(Object)("Salvo em:"));
 //BA.debugLineNum = 287;BA.debugLine="Texts.Put(\"backup_error\", \"Erro ao criar backup\")";
_texts.Put((Object)("backup_error"),(Object)("Erro ao criar backup"));
 //BA.debugLineNum = 288;BA.debugLine="Texts.Put(\"backup_none_found\", \"Nenhum arquivo .l";
_texts.Put((Object)("backup_none_found"),(Object)("Nenhum arquivo .lockzero encontrado"));
 //BA.debugLineNum = 289;BA.debugLine="Texts.Put(\"backup_phrase_backup\", \"Frase do backu";
_texts.Put((Object)("backup_phrase_backup"),(Object)("Frase do backup"));
 //BA.debugLineNum = 290;BA.debugLine="Texts.Put(\"backup_enter_phrase\", \"Digite a frase";
_texts.Put((Object)("backup_enter_phrase"),(Object)("Digite a frase usada ao criar o backup:"));
 //BA.debugLineNum = 291;BA.debugLine="Texts.Put(\"backup_confirm_restore\", \"ATENÇÃO: Iss";
_texts.Put((Object)("backup_confirm_restore"),(Object)("ATENÇÃO: Isso irá adicionar os dados do backup aos seus dados atuais."));
 //BA.debugLineNum = 292;BA.debugLine="Texts.Put(\"backup_continue\", \"Deseja continuar?\")";
_texts.Put((Object)("backup_continue"),(Object)("Deseja continuar?"));
 //BA.debugLineNum = 293;BA.debugLine="Texts.Put(\"backup_restored\", \"Backup restaurado!\"";
_texts.Put((Object)("backup_restored"),(Object)("Backup restaurado!"));
 //BA.debugLineNum = 294;BA.debugLine="Texts.Put(\"backup_groups\", \"Grupos:\")";
_texts.Put((Object)("backup_groups"),(Object)("Grupos:"));
 //BA.debugLineNum = 295;BA.debugLine="Texts.Put(\"backup_entries\", \"Senhas:\")";
_texts.Put((Object)("backup_entries"),(Object)("Senhas:"));
 //BA.debugLineNum = 296;BA.debugLine="Texts.Put(\"backup_notes\", \"Notas:\")";
_texts.Put((Object)("backup_notes"),(Object)("Notas:"));
 //BA.debugLineNum = 297;BA.debugLine="Texts.Put(\"backup_valid\", \"Backup VÁLIDO!\")";
_texts.Put((Object)("backup_valid"),(Object)("Backup VÁLIDO!"));
 //BA.debugLineNum = 298;BA.debugLine="Texts.Put(\"backup_created_at\", \"Criado em:\")";
_texts.Put((Object)("backup_created_at"),(Object)("Criado em:"));
 //BA.debugLineNum = 299;BA.debugLine="Texts.Put(\"backup_test_ok\", \"Teste OK\")";
_texts.Put((Object)("backup_test_ok"),(Object)("Teste OK"));
 //BA.debugLineNum = 300;BA.debugLine="Texts.Put(\"backup_test_failed\", \"Frase incorreta";
_texts.Put((Object)("backup_test_failed"),(Object)("Frase incorreta ou arquivo corrompido"));
 //BA.debugLineNum = 301;BA.debugLine="Texts.Put(\"backup_wrong_phrase\", \"Frase incorreta";
_texts.Put((Object)("backup_wrong_phrase"),(Object)("Frase incorreta ou arquivo corrompido"));
 //BA.debugLineNum = 302;BA.debugLine="Texts.Put(\"backup_share_question\", \"Deseja compar";
_texts.Put((Object)("backup_share_question"),(Object)("Deseja compartilhar o arquivo de backup?"));
 //BA.debugLineNum = 303;BA.debugLine="Texts.Put(\"share\", \"Compartilhar\")";
_texts.Put((Object)("share"),(Object)("Compartilhar"));
 //BA.debugLineNum = 304;BA.debugLine="Texts.Put(\"share_error\", \"Erro ao compartilhar\")";
_texts.Put((Object)("share_error"),(Object)("Erro ao compartilhar"));
 //BA.debugLineNum = 305;BA.debugLine="End Sub";
return "";
}
public static String  _loadtexts(anywheresoftware.b4a.BA _ba) throws Exception{
 //BA.debugLineNum = 48;BA.debugLine="Private Sub LoadTexts";
 //BA.debugLineNum = 49;BA.debugLine="Texts.Initialize";
_texts.Initialize();
 //BA.debugLineNum = 51;BA.debugLine="Select CurrentLang";
switch (BA.switchObjectToInt(_currentlang,"en")) {
case 0: {
 //BA.debugLineNum = 52;BA.debugLine="Case \"en\": LoadEnglish";
_loadenglish(_ba);
 break; }
default: {
 //BA.debugLineNum = 53;BA.debugLine="Case Else: LoadPortuguese";
_loadportuguese(_ba);
 break; }
}
;
 //BA.debugLineNum = 55;BA.debugLine="End Sub";
return "";
}
public static String  _process_globals() throws Exception{
 //BA.debugLineNum = 5;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 6;BA.debugLine="Private CurrentLang As String = \"pt\"";
_currentlang = "pt";
 //BA.debugLineNum = 7;BA.debugLine="Private Texts As Map";
_texts = new anywheresoftware.b4a.objects.collections.Map();
 //BA.debugLineNum = 8;BA.debugLine="End Sub";
return "";
}
public static String  _setlanguage(anywheresoftware.b4a.BA _ba,String _langcode) throws Exception{
 //BA.debugLineNum = 16;BA.debugLine="Public Sub SetLanguage(langCode As String)";
 //BA.debugLineNum = 17;BA.debugLine="CurrentLang = langCode.ToLowerCase";
_currentlang = _langcode.toLowerCase();
 //BA.debugLineNum = 18;BA.debugLine="ModSecurity.SaveLanguage(CurrentLang)";
mostCurrent._modsecurity._savelanguage /*String*/ (_ba,_currentlang);
 //BA.debugLineNum = 19;BA.debugLine="LoadTexts";
_loadtexts(_ba);
 //BA.debugLineNum = 20;BA.debugLine="End Sub";
return "";
}
public static String  _t(anywheresoftware.b4a.BA _ba,String _key) throws Exception{
 //BA.debugLineNum = 35;BA.debugLine="Public Sub T(key As String) As String";
 //BA.debugLineNum = 36;BA.debugLine="If Texts.IsInitialized = False Then LoadTexts";
if (_texts.IsInitialized()==anywheresoftware.b4a.keywords.Common.False) { 
_loadtexts(_ba);};
 //BA.debugLineNum = 37;BA.debugLine="If Texts.ContainsKey(key) Then";
if (_texts.ContainsKey((Object)(_key))) { 
 //BA.debugLineNum = 38;BA.debugLine="Return Texts.Get(key)";
if (true) return BA.ObjectToString(_texts.Get((Object)(_key)));
 };
 //BA.debugLineNum = 40;BA.debugLine="Return key 'Retorna a chave se nao encontrar";
if (true) return _key;
 //BA.debugLineNum = 41;BA.debugLine="End Sub";
return "";
}
}
